### ISSUE TITLE
DIC crashes when dumping a remote USB floppy drive

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#241]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Description

Trying to dump from a USB floppy drive on a remote computer crashes DIC with "Unhandled Exception: System.ArgumentNullException: Value cannot be null."

### Exact command line used:

`dotnet discimagechef.dll dump-media dic://(my IP)/dev/sdb test.dicf -d`

### If command was expected to work with a device fill this:

* **Manufacturer**:
* **Model**:
* **Bus**:
    * [ ] Parallel ATA
    * [ ] Serial ATA
    * [ ] SCSI (any)
    * [ ] ATAPI (mark above if parallel or serial)
    * [X] USB
    * [ ] FireWire
    * [ ] PCMCIA
    * [ ] SecureDigital
    * [ ] MultiMediaCard
    
### Output of command execution with debug output enabled
```
DiscImageChef 4.5.99.1693-00000000 built by DESKTOP-8B4K7NM in Debug
Copyright c 2011-2019 Natalia Portillo

DEBUG (Dump-Media command): --cicm-xml=
DEBUG (Dump-Media command): --debug=True
DEBUG (Dump-Media command): --device=dic://(my IP)/dev/sdb
DEBUG (Dump-Media command): --encoding=
DEBUG (Dump-Media command): --first-pregap=False
DEBUG (Dump-Media command): --force=False
DEBUG (Dump-Media command): --force=False
DEBUG (Dump-Media command): --format=
DEBUG (Dump-Media command): --no-metadata=False
DEBUG (Dump-Media command): --options=Mono.Options.OptionSet
DEBUG (Dump-Media command): --output=test.dicf
DEBUG (Dump-Media command): --persistent=False
DEBUG (Dump-Media command): --resume=True
DEBUG (Dump-Media command): --retry-passes=5
DEBUG (Dump-Media command): --skip=512
DEBUG (Dump-Media command): --stop-on-error=False
DEBUG (Dump-Media command): --verbose=False
DEBUG (Dump-Media command): Parsed options:
Connected to (my IP)
DEBUG (SCSI Device): INQUIRY took 16 ms.
Uploading statistics
DEBUG (SCSI Device): INQUIRY took 320 ms.
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 748 ms.
Output image format: DiscImageChef format.
DEBUG (SCSI Device): TEST UNIT READY took 16 ms.

DEBUG (SCSI Device): READ CAPACITY took 308 ms.
DEBUG (SCSI Device): READ (6) took 24 ms.
DEBUG (SCSI Device): READ (10) took 268 ms.
DEBUG (SCSI Device): READ (12) took 396 ms.
DEBUG (SCSI Device): READ (16) took 268 ms.
DEBUG (SCSI Device): SEEK (6) took 32 ms.
DEBUG (SCSI Device): SEEK (10) took 32 ms.
Using SCSI READ (12) command.
Media has 2880 blocks of 512 bytes/each. (for a total of 1474560 bytes)
DEBUG (SCSI Device): READ (12) took 960 ms.
DEBUG (SCSI Device): INQUIRY took 32 ms.
Requesting MODE SENSE (10).
DEBUG (SCSI Device): MODE SENSE(10) took 24 ms.
DEBUG (SCSI Device): MODE SENSE(10) took 28 ms.
Requesting MODE SENSE (6).

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at DiscImageChef.Core.Devices.Dumping.Dump.Sbc(Dictionary`2 mediaTags, MediaType& dskType, Boolean opticalDisc) in C:\Users\silas\Desktop\GIT\DiscImageChef\trunk\DiscImageChef.Core\Devices\Dumping\SBC.cs:line 178
   at DiscImageChef.Core.Devices.Dumping.Dump.Scsi() in C:\Users\silas\Desktop\GIT\DiscImageChef\trunk\DiscImageChef.Core\Devices\Dumping\SCSI.cs:line 214
   at DiscImageChef.Core.Devices.Dumping.Dump.Start() in C:\Users\silas\Desktop\GIT\DiscImageChef\trunk\DiscImageChef.Core\Devices\Dumping\Dump.cs:line 118
   at DiscImageChef.Commands.DumpMediaCommand.Invoke(IEnumerable`1 arguments) in C:\Users\silas\Desktop\GIT\DiscImageChef\trunk\DiscImageChef\Commands\DumpMedia.cs:line 307
   at Mono.Options.CommandSet.Run(IEnumerable`1 arguments)
   at DiscImageChef.MainClass.Main(String[] args) in C:\Users\silas\Desktop\GIT\DiscImageChef\trunk\DiscImageChef\Main.cs:line 157
```

**Comment by claunia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Crash when dumping from a remote USB floppy drive](https://trello.com/c/icVZK9dy/11-crash-when-dumping-from-a-remote-usb-floppy-drive)

**Comment by SilasLaspada** [comment]
Fixed at some point since last time I tested this.
