### ISSUE TITLE
New unsupported Alcohol 120% image version.

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#285]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Description

Most, if not all, image commands fail when handling a specific MDS image (not dumped by myself so information is limited, but I can ask the person who made it questions about it), with seemingly all of the errors being "Error: An item with the same key has already been added. Key: 0". Check and verify crash chef with "Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: An item with the same key has already been added. Key: 0". Link to the image: https://drive.google.com/file/d/0B5CLvVy7TRT5VVNYaDIyWXpyUkE/view?usp=sharing

### Exact command line used:

` dotnet .\DiscImageChef.dll --debug image verify ".\CNQN04992Q4.mds"`

### Output of command execution with debug output enabled
```
DiscImageChef 4.5.99.1693-63fd68fe built by DESKTOP-8B4K7NM in Debug, modified
Copyright c 2011-2020 Natalia Portillo

DEBUG (Verify command): --debug=True
DEBUG (Verify command): --input=.\CNQN04992Q4.mds
DEBUG (Verify command): --verbose=False
DEBUG (Verify command): --verify-disc=True
DEBUG (Verify command): --verify-sectors=True
DEBUG (Format detection): Trying plugin ACT Apricot Disk Image
DEBUG (Format detection): Trying plugin Alcohol 120% Media Descriptor Structure
DEBUG (Alcohol 120% plugin): header.signature = MEDIA DESCRIPTOR
DEBUG (Alcohol 120% plugin): header.version = 2.1
DEBUG (Alcohol 120% plugin): header.type = 8361
DEBUG (Alcohol 120% plugin): header.sessions = 12338
DEBUG (Alcohol 120% plugin): header.unknown1[0] = 0x3030
DEBUG (Alcohol 120% plugin): header.unknown1[1] = 0x322D
DEBUG (Alcohol 120% plugin): header.bcaLength = 12592
DEBUG (Alcohol 120% plugin): header.unknown2[0] = 0x69442035
DEBUG (Alcohol 120% plugin): header.unknown2[1] = 0x53206373
DEBUG (Alcohol 120% plugin): header.bcaOffset = 544499311
DEBUG (Alcohol 120% plugin): header.unknown3[0] = 0x2E64744C
DEBUG (Alcohol 120% plugin): header.unknown3[1] = 0x000000B0
DEBUG (Alcohol 120% plugin): header.unknown3[2] = 0x181452CC
DEBUG (Alcohol 120% plugin): header.unknown3[3] = 0x111D5BD5
DEBUG (Alcohol 120% plugin): header.unknown3[4] = 0xD4234818
DEBUG (Alcohol 120% plugin): header.unknown3[5] = 0xAF432770
DEBUG (Alcohol 120% plugin): header.structuresOffset = 1649492139
DEBUG (Alcohol 120% plugin): header.unknown4[0] = 0x59BC08A2
DEBUG (Alcohol 120% plugin): header.unknown4[1] = 0xE3529DF0
DEBUG (Alcohol 120% plugin): header.unknown4[2] = 0xAE7F08E0
DEBUG (Alcohol 120% plugin): header.sessionOffset = 1969351191
DEBUG (Alcohol 120% plugin): header.dpmOffset = 2804548799
DEBUG (Alcohol 120% plugin): session[0].sessionStart = 0
DEBUG (Alcohol 120% plugin): session[0].sessionEnd = 0
DEBUG (Alcohol 120% plugin): session[0].sessionSequence = 0
DEBUG (Alcohol 120% plugin): session[0].allBlocks = 0
DEBUG (Alcohol 120% plugin): session[0].nonTrackBlocks = 0
DEBUG (Alcohol 120% plugin): session[0].firstTrack = 0
DEBUG (Alcohol 120% plugin): session[0].lastTrack = 0
DEBUG (Alcohol 120% plugin): session[0].unknown = 0x00000000
DEBUG (Alcohol 120% plugin): session[0].trackOffset = 0
DEBUG (Alcohol 120% plugin): session[1].sessionStart = 0
DEBUG (Alcohol 120% plugin): session[1].sessionEnd = 0
DEBUG (Alcohol 120% plugin): session[1].sessionSequence = 0
DEBUG (Alcohol 120% plugin): session[1].allBlocks = 0
DEBUG (Alcohol 120% plugin): session[1].nonTrackBlocks = 0
DEBUG (Alcohol 120% plugin): session[1].firstTrack = 0
DEBUG (Alcohol 120% plugin): session[1].lastTrack = 0
DEBUG (Alcohol 120% plugin): session[1].unknown = 0x00000000
DEBUG (Alcohol 120% plugin): session[1].trackOffset = 0
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: An item with the same key has already been added. Key: 0
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at DiscImageChef.DiscImages.Alcohol120.Open(IFilter imageFilter) in C:\Users\silas\Desktop\GIT\DICF\DiscImageChef\DiscImageChef.DiscImages\Alcohol120\Read.cs:line 133
   at DiscImageChef.Commands.Image.VerifyCommand.Invoke(Boolean debug, Boolean verbose, String imagePath, Boolean verifyDisc, Boolean verifySectors) in C:\Users\silas\Desktop\GIT\DICF\DiscImageChef\DiscImageChef\Commands\Image\Verify.cs:line 112
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.<InvokeAsync>d__8.MoveNext() in /_/src/System.CommandLine/Invocation/ModelBindingCommandHandler.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationPipeline.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseErrorReporting>b__22_0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 367
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass8_0.<<UseTypoCorrections>b__0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 225
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseSuggestDirective>b__7_0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseDirective>b__6_0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 177
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseHelp>b__20_0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 335
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass4_0.<<UseVersionOption>b__0>d.MoveNext() in /_/src/System.CommandLine/Builder/CommandLineBuilderExtensions.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<RegisterWithDotnetSuggest>b__23_0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 406
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass5_0.<<UseExceptionHandler>b__0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 142
```

**Comment by claunia** [comment]
@SilasLaspada this is a new image format altogether, ask your friend what version of Alcohol 120% did he use to create it.

**Comment by SilasLaspada** [comment]
I’ve emailed them, in the mean time if you need more image files presumably in the same format, they sent me a few different images that I haven’t checked but I assume would’ve been the same format.

**Comment by claunia** [comment]
Just images would not be enough I need to know the exact software used to create them.

**Comment by SilasLaspada** [comment]
Alright, I’ll let you know what they used as soon as I do!

**Comment by SilasLaspada** [comment]
This should be the tool that was used as far as I can tell: https://www.betaarchive.com/files/A120FE_9902_PE.zip

**Comment by SilasLaspada** [comment]
Duplicate of #256.
