### ISSUE TITLE
Unhandled exception when running media dump and info

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#290]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [X] ...in 64-bit

### Description

Trying to dump a disc or run media info causes Aaru to crash on my system. Msinfo32 in case it's needed: [msinfo32.zip](https://github.com/aaru-dps/Aaru/files/4288578/msinfo32.zip)

### Output of command execution with debug output enabled
```
Aaru 4.5.99.2020-18db5ed8 built by DESKTOP-8B4K7NM in Debug, modified
Copyright c 2011-2020 Natalia Portillo

DEBUG (Media-Info command): --debug=True
DEBUG (Media-Info command): --device=G:
DEBUG (Media-Info command): --output-prefix=
DEBUG (Media-Info command): --verbose=False
DEBUG (SCSI Device): INQUIRY took 0.4738 ms.
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 2.611 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 264, Return Type: Single, Sense: False, Last Error: 0) took 0.3219 ms.
DEBUG (SCSI Device): TEST UNIT READY took 0.1712 ms.
DEBUG (SCSI Device): INQUIRY took 0.439 ms.
DEBUG (SCSI Device): MODE SENSE(10) took 0.3812 ms.
DEBUG (SCSI Device): MODE SENSE(10) took 0.9658 ms.
DEBUG (SCSI Device): MODE SENSE(6) took 1.1598 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 0, Return Type: All, Sense: False, Last Error: 0) took 0.9335 ms.
DEBUG (SCSI Device): PLEXTOR READ EEPROM took 0.7767 ms.
DEBUG (SCSI Device): PLEXTOR POWEREC GET SPEEDS took 0.3029 ms.
DEBUG (SCSI Device): PLEXTOR POWEREC GET SPEEDS took 0.253 ms.
DEBUG (SCSI Device): PLEXTOR GET SILENT MODE took 0.4241 ms.
DEBUG (SCSI Device): PLEXTOR GET GIGAREC took 0.3886 ms.
DEBUG (SCSI Device): PLEXTOR GET SECUREC took 0.3554 ms.
DEBUG (SCSI Device): PLEXTOR GET SPEEDREAD took 0.3366 ms.
DEBUG (SCSI Device): PLEXTOR GET SINGLE-SESSION / HIDE CD-R took 0.2474 ms.
DEBUG (SCSI Device): PLEXTOR GET VARIREC took 0.2307 ms.
DEBUG (SCSI Device): READ CAPACITY took 0.236 ms.
DEBUG (SCSI Device): READ CAPACITY(16) took 0.3173 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 0, Return Type: Current, Sense: False, Last Error: 0) took 0.7313 ms.
DEBUG (Media-Info command): GET CONFIGURATION current profile is 0008h
Uploading statistics
DEBUG (Media-Info command): READ DISC STRUCTURE: Recognized Format Layers
SCSI SENSE: ILLEGAL REQUEST
INVALID COMMAND OPERATION CODE

DEBUG (Media-Info command): READ DISC STRUCTURE: Write Protection Status
SCSI SENSE: ILLEGAL REQUEST
INVALID COMMAND OPERATION CODE

DEBUG (SCSI Device): READ TOC/PMA/ATIP took (MSF: False, Format: 0, Track/Session Number: 0, Sense: False, LastError: 0) 0.3713 ms.
DEBUG (SCSI Device): READ TOC/PMA/ATIP took (MSF: True, Format: 4, Track/Session Number: 0, Sense: False, LastError: 0) 0.2885 ms.
DEBUG (CD ATIP decoder): Expected CD ATIP size (32 bytes) is not received size (4 bytes), not decoding
DEBUG (SCSI Device): READ DISC INFORMATION (Data Type: DiscInformation, Sense: False, Last Error: 0) took 0.4504 ms.
DEBUG (SCSI Device): READ TOC/PMA/ATIP took (MSF: True, Format: 1, Track/Session Number: 0, Sense: False, LastError: 0) 0.2819 ms.
DEBUG (SCSI Device): READ TOC/PMA/ATIP took (MSF: True, Format: 2, Track/Session Number: 1, Sense: False, LastError: 0) 0.5478 ms.
DEBUG (SCSI Device): READ TOC/PMA/ATIP took (MSF: True, Format: 3, Track/Session Number: 0, Sense: False, LastError: 0) 0.3089 ms.
DEBUG (SCSI Device): READ TOC/PMA/ATIP took (MSF: True, Format: 5, Track/Session Number: 0, Sense: False, LastError: 87) 0.0165 ms.
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Aaru.Decoders.CD.CDTextOnLeadIn.Decode(Byte[] CDTextResponse) in C:\Users\silas\Desktop\GIT\Aaru\Aaru\Aaru.Decoders\CD\CDTextOnLeadIn.cs:line 90
   at Aaru.Core.Media.Info.ScsiInfo..ctor(Device dev) in C:\Users\silas\Desktop\GIT\Aaru\Aaru\Aaru.Core\Media\Info\ScsiInfo.cs:line 1191
   at Aaru.Commands.Media.MediaInfoCommand.DoScsiMediaInfo(Boolean debug, Boolean verbose, String outputPrefix, Device dev) in C:\Users\silas\Desktop\GIT\Aaru\Aaru\Aaru\Commands\Media\Info.cs:line 168
   at Aaru.Commands.Media.MediaInfoCommand.Invoke(Boolean debug, Boolean verbose, String devicePath, String outputPrefix) in C:\Users\silas\Desktop\GIT\Aaru\Aaru\Aaru\Commands\Media\Info.cs:line 150
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.<InvokeAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseErrorReporting>b__22_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass8_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseSuggestDirective>b__7_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseDirective>b__6_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseHelp>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass4_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<RegisterWithDotnetSuggest>b__23_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass5_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by SilasLaspada** [comment]
Fixed by recent commit.
