### ISSUE TITLE
GUI crashes when running several commands after enabling debug console when running as root

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#340]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Description

The GUI crashes when calculating entropy, verifying, checksumming, and possibly more after enabling debug output in the console when the GUI is run with sudo. Doesn't crash with debug output disabled, or when not running as sudo. The following is printed to the console: 
"Unhandled exception. System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess()
   at Avalonia.AvaloniaObject.GetValue(AvaloniaProperty property)
   at Avalonia.AvaloniaObject.GetValue[T](AvaloniaProperty`1 property)
   at Avalonia.Controls.DataGrid.InsertElementAt(Int32 slot, Int32 rowIndex, Object item, DataGridRowGroupInfo groupInfo, Boolean isCollapsed)
   at Avalonia.Controls.DataGrid.InsertRowAt(Int32 rowIndex)
   at Avalonia.Collections.DataGridCollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   at Avalonia.Collections.DataGridCollectionView.ProcessAddEvent(Object addedItem, Int32 addIndex)
   at Avalonia.Collections.DataGridCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at Avalonia.Collections.DataGridCollectionView.<.ctor>b__27_0(Object _, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at Aaru.Gui.ConsoleHandler.OnWriteHandler(String format, Object[] arg) in /home/silas/Desktop/Aaru/Aaru.Gui/ConsoleHandler.cs:line 93
   at Aaru.Console.AaruConsole.WriteLine(String format, Object[] arg) in /home/silas/Desktop/Aaru/Aaru.Console/AaruConsole.cs:line 70
   at Aaru.Gui.ViewModels.Windows.ImageEntropyViewModel.<>c__DisplayClass131_0.<<ExecuteStartCommand>b__0>d.MoveNext() in /home/silas/Desktop/Aaru/Aaru.Gui/ViewModels/Windows/ImageEntropyViewModel.cs:line 310
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Aborted"

**Comment by claunia** [comment]
Fixed already.
