### ISSUE TITLE
Extracting CD-i Movie causes crash

### ISSUE THREAD

**Issue by mnadareski** [aaru-dps/Aaru#369]
### Prerequisites

* [x] Are you running the latest version?
* [x] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [x] I was running Aaru under Windows 10...
* [x] ...using .NET Core 3.1...
* [x] ...in 64-bit

### Description

While extracting the contents of a CD-i Movie dumped with Aaru to AIF, it crashed with the following:
```
Error reading file: Sector address 1661534208 not found (Parameter 'sectorAddress')
DEBUG (Extract-Files command):    at Aaru.DiscImages.AaruFormat.ReadSector(UInt64 sectorAddress) in B:\Programs\GitHub\Aaru\Aaru.Images\AaruFormat\Read.cs:line 1250
   at Aaru.Filesystems.ISO9660.ISO9660.ReadSector(UInt64 sector, Boolean interleaved, Byte fileNumber) in B:\Programs\GitHub\Aaru\Aaru.Filesystems\ISO9660\Mode2.cs:line 52
   at Aaru.Filesystems.ISO9660.ISO9660.ReadWithExtents(Int64 offset, Int64 size, List`1 extents, Boolean interleaved, Byte fileNumber) in B:\Programs\GitHub\Aaru\Aaru.Filesystems\ISO9660\File.cs:line 518
   at Aaru.Filesystems.ISO9660.ISO9660.Read(String path, Int64 offset, Int64 size, Byte[]& buf) in B:\Programs\GitHub\Aaru\Aaru.Filesystems\ISO9660\File.cs:line 157
   at Aaru.Commands.Filesystem.ExtractFilesCommand.ExtractFilesInDir(String path, IReadOnlyFilesystem fs, String volumeName, String outputDir, Boolean doXattrs) in B:\Programs\GitHub\Aaru\Aaru\Commands\Filesystem\ExtractFiles.cs:line 476
   at Aaru.Commands.Filesystem.ExtractFilesCommand.Invoke(Boolean debug, Boolean verbose, String encoding, Boolean xattrs, String imagePath, String namespace, String outputDir, String options) in B:\Programs\GitHub\Aaru\Aaru\Commands\Filesystem\ExtractFiles.cs:line 307
```

### Exact command line used:

`Aaru --debug filesystem extract B:\_TEMP\T2_DISC_1.aif B:\_TEMP\T2_DISC_1`

### Expected behavior:
Full contents extraction

### Actual behavior:
Incomplete extraction

**Comment by mnadareski** [comment]
With the changes pushed to support the Rainbow disc, this issue has cleared up. Not sure why, but it works now.
