### ISSUE TITLE
Converting B6T image to other formats crashes Aaru

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#379]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [X] ...in 64-bit

### Description

Converting a B6T image from BlindWrite 6 to aaruf crashes Aaru with 
"Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation."
Image file: [Sony USB Driver B6T.zip](https://github.com/aaru-dps/Aaru/files/4969775/Sony.USB.Driver.B6T.zip)

### Exact command line used:

`aaru -d i convert '.\Sony USB Driver.B6T' ./sonyb6ttoaaruf.aaruf`

### Output of command execution with debug output enabled
```
aaru 5.0.99.2991+9a202e02 built by DESKTOP-8B4K7NM in Debug
Copyright c 2011-2020 Natalia Portillo

DEBUG (Image convert command): --cicm-xml=
DEBUG (Image convert command): --comments=
DEBUG (Image convert command): --count=64
DEBUG (Image convert command): --creator=
DEBUG (Image convert command): --debug=True
DEBUG (Image convert command): --drive-manufacturer=
DEBUG (Image convert command): --drive-model=
DEBUG (Image convert command): --drive-revision=
DEBUG (Image convert command): --drive-serial=
DEBUG (Image convert command): --force=False
DEBUG (Image convert command): --format=
DEBUG (Image convert command): --geometry=
DEBUG (Image convert command): --input=.\Sony USB Driver.B6T
DEBUG (Image convert command): --media-barcode=
DEBUG (Image convert command): --media-lastsequence=0
DEBUG (Image convert command): --media-manufacturer=
DEBUG (Image convert command): --media-model=
DEBUG (Image convert command): --media-partnumber=
DEBUG (Image convert command): --media-sequence=0
DEBUG (Image convert command): --media-serial=
DEBUG (Image convert command): --media-title=
DEBUG (Image convert command): --options=
DEBUG (Image convert command): --output=./sonyb6ttoaaruf.aaruf
DEBUG (Image convert command): --resume-file=
DEBUG (Image convert command): --verbose=False
DEBUG (Image convert command): --fix-subchannel-position=True
DEBUG (Image convert command): --fix-subchannel=False
DEBUG (Image convert command): --fix-subchannel-crc=False
DEBUG (Image convert command): --generate-subchannels=False
DEBUG (Analyze command): Parsed options:
DEBUG (Format detection): Trying plugin Aaru Format
DEBUG (Format detection): Trying plugin ACT Apricot Disk Image
DEBUG (Format detection): Trying plugin Alcohol 120% Media Descriptor Structure
DEBUG (Format detection): Trying plugin Anex86 Disk Image
DEBUG (Anex86 plugin): fdihdr.unknown = 894719810
DEBUG (Anex86 plugin): fdihdr.hddtype = 1381258016
DEBUG (Anex86 plugin): fdihdr.hdrSize = 541933893
DEBUG (Anex86 plugin): fdihdr.dskSize = 1313294675
DEBUG (Anex86 plugin): fdihdr.bps = 2
DEBUG (Anex86 plugin): fdihdr.spt = 2
DEBUG (Anex86 plugin): fdihdr.heads = 6
DEBUG (Anex86 plugin): fdihdr.cylinders = 0
DEBUG (Format detection): Trying plugin Apple ][ Interleaved Disk Image
DEBUG (Format detection): Trying plugin Apple 2IMG
DEBUG (Format detection): Trying plugin Apple Disk Archival/Retrieval Tool
DEBUG (Format detection): Trying plugin Apple DiskCopy 4.2
DEBUG (Format detection): Trying plugin Apple New Disk Image Format
DEBUG (Format detection): Trying plugin Apple NIB
DEBUG (Format detection): Trying plugin Apple Universal Disk Image Format
DEBUG (Format detection): Trying plugin Basic Lisa Utility
DEBUG (Format detection): Trying plugin BlindWrite 4
DEBUG (Format detection): Trying plugin BlindWrite 5
Input image format identified by BlindWrite 5.
DEBUG (BlindWrite5 plugin): header.signature = BWT5 STREAM SIGN
DEBUG (BlindWrite5 plugin): header.unknown1[0] = 0x00000002
DEBUG (BlindWrite5 plugin): header.unknown1[1] = 0x00000002
DEBUG (BlindWrite5 plugin): header.unknown1[2] = 0x00000006
DEBUG (BlindWrite5 plugin): header.unknown1[3] = 0x00000000
DEBUG (BlindWrite5 plugin): header.unknown1[4] = 0x00000000
DEBUG (BlindWrite5 plugin): header.unknown1[5] = 0x00000000
DEBUG (BlindWrite5 plugin): header.unknown1[6] = 0x00000000
DEBUG (BlindWrite5 plugin): header.unknown1[7] = 0x00000000
DEBUG (BlindWrite5 plugin): header.profile = CDROM
DEBUG (BlindWrite5 plugin): header.sessions = 1
DEBUG (BlindWrite5 plugin): header.unknown2[0] = 0x00000002
DEBUG (BlindWrite5 plugin): header.unknown2[1] = 0x00000000
DEBUG (BlindWrite5 plugin): header.unknown2[2] = 0x00000000
DEBUG (BlindWrite5 plugin): header.mcnIsValid = False
DEBUG (BlindWrite5 plugin): header.mcn = 0000000000000
DEBUG (BlindWrite5 plugin): header.unknown3 = 0x0000
DEBUG (BlindWrite5 plugin): header.unknown4[0] = 0x00000000
DEBUG (BlindWrite5 plugin): header.unknown4[1] = 0x00000000
DEBUG (BlindWrite5 plugin): header.unknown4[2] = 0x00000000
DEBUG (BlindWrite5 plugin): header.unknown4[3] = 0x00000000
DEBUG (BlindWrite5 plugin): header.pmaLen = 0
DEBUG (BlindWrite5 plugin): header.atipLen = 0
DEBUG (BlindWrite5 plugin): header.cdtLen = 0
DEBUG (BlindWrite5 plugin): header.cdInfoLen = 56
DEBUG (BlindWrite5 plugin): header.bcaLen = 0
DEBUG (BlindWrite5 plugin): header.unknown5[0] = 0x00000000
DEBUG (BlindWrite5 plugin): header.unknown5[1] = 0x00000000
DEBUG (BlindWrite5 plugin): header.unknown5[2] = 0x00000000
DEBUG (BlindWrite5 plugin): header.dvdStrLen = 0
DEBUG (BlindWrite5 plugin): header.dvdInfoLen = 0
DEBUG (BlindWrite5 plugin): header.unknown6[0] = 0xA6
DEBUG (BlindWrite5 plugin): header.unknown6[1] = 0x85
DEBUG (BlindWrite5 plugin): header.unknown6[2] = 0x13
DEBUG (BlindWrite5 plugin): header.unknown6[3] = 0x5F
DEBUG (BlindWrite5 plugin): header.unknown6[4] = 0x9B
DEBUG (BlindWrite5 plugin): header.unknown6[5] = 0x1B
DEBUG (BlindWrite5 plugin): header.unknown6[6] = 0x24
DEBUG (BlindWrite5 plugin): header.unknown6[7] = 0x27
DEBUG (BlindWrite5 plugin): header.unknown6[8] = 0x2B
DEBUG (BlindWrite5 plugin): header.unknown6[9] = 0xF9
DEBUG (BlindWrite5 plugin): header.unknown6[10] = 0x67
DEBUG (BlindWrite5 plugin): header.unknown6[11] = 0x33
DEBUG (BlindWrite5 plugin): header.unknown6[12] = 0x3E
DEBUG (BlindWrite5 plugin): header.unknown6[13] = 0x61
DEBUG (BlindWrite5 plugin): header.unknown6[14] = 0x29
DEBUG (BlindWrite5 plugin): header.unknown6[15] = 0x46
DEBUG (BlindWrite5 plugin): header.unknown6[16] = 0x3F
DEBUG (BlindWrite5 plugin): header.unknown6[17] = 0x01
DEBUG (BlindWrite5 plugin): header.unknown6[18] = 0xFD
DEBUG (BlindWrite5 plugin): header.unknown6[19] = 0x88
DEBUG (BlindWrite5 plugin): header.unknown6[20] = 0x01
DEBUG (BlindWrite5 plugin): header.unknown6[21] = 0x0E
DEBUG (BlindWrite5 plugin): header.unknown6[22] = 0x00
DEBUG (BlindWrite5 plugin): header.unknown6[23] = 0x02
DEBUG (BlindWrite5 plugin): header.unknown6[24] = 0x00
DEBUG (BlindWrite5 plugin): header.unknown6[25] = 0x00
DEBUG (BlindWrite5 plugin): header.unknown6[26] = 0x00
DEBUG (BlindWrite5 plugin): header.unknown6[27] = 0x00
DEBUG (BlindWrite5 plugin): header.unknown6[28] = 0x00
DEBUG (BlindWrite5 plugin): header.unknown6[29] = 0x00
DEBUG (BlindWrite5 plugin): header.unknown6[30] = 0x00
DEBUG (BlindWrite5 plugin): header.unknown6[31] = 0x00
DEBUG (BlindWrite5 plugin): header.manufacturer = Memorex
DEBUG (BlindWrite5 plugin): header.product = MRX-650LE v7
DEBUG (BlindWrite5 plugin): header.revision = 1.00
DEBUG (BlindWrite5 plugin): header.vendor = 14062000
DEBUG (BlindWrite5 plugin): header.volumeId = Sony USB Driver
DEBUG (BlindWrite5 plugin): header.mode2ALen = 66
DEBUG (BlindWrite5 plugin): header.unkBlkLen = 4
DEBUG (BlindWrite5 plugin): header.dataLen = 174
DEBUG (BlindWrite5 plugin): header.sessionsLen = 280
DEBUG (BlindWrite5 plugin): header.dpmLen = 0
DEBUG (BlindWrite5 plugin): mode page 2A: SCSI CD-ROM capabilities page:
        Drive can play audio
        Drive can read sectors in Mode 2 Form 1 format
        Drive can read sectors in Mode 2 Form 2 format
        Drive supports multi-session discs and/or Photo-CD
        Drive can read digital audio
        Drive can continue from streaming loss
        Drive can read uncorrected and interleaved R-W subchannels
        Drive can read, deinterleave and correct R-W subchannels
        Drive supports C2 pointers
        Drive can read Media Catalogue Number
        Drive can read ISRC
        Drive uses a tray
        Drive can lock media
        Drive is not locked, media can be ejected and inserted
        Drive can eject media
        Drive has 768 Kbyte of buffer
        Drive's maximum reading speed is 4234 Kbyte/sec.
        Drive's current reading speed is 4234 Kbyte/sec.
        Drive can read and write CD-R
        Drive supports reading CD-R packet media
        Drive can read and write CD-RW
        Drive can read DVD-ROM
        Drive can read and write DVD-R
        Drive can read and write DVD-RAM
        Drive supports test writing
        Drive can read both sides of a disc
        Drive an read raw R-W subchannel from the Lead-In
        Drive supports DVD CSS and/or DVD CPPM
        Drive supports buffer under-run free recording

DEBUG (BlindWrite5 plugin): Disc information: Offset   00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
000000   01 00 00 00 00 00 00 00 25 00 00 00 00 00 00 00   ........%.......
000010   00 00 00 00 00 00 00 00 FF 00 00 00 00 00 00 00   ........ÿ.......
000020   00 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00   ................
000030   00 00 04 1C 00 00 08 00                           ........

DEBUG (BlindWrite5 plugin): Data path: C:\Users\silas\Documents\BlindWrite\
DEBUG (BlindWrite5 plugin): dataFile.type = 0xFF000500
DEBUG (BlindWrite5 plugin): dataFile.length = 2829456
DEBUG (BlindWrite5 plugin): dataFile.unknown1[0] = 0
DEBUG (BlindWrite5 plugin): dataFile.unknown1[1] = 0
DEBUG (BlindWrite5 plugin): dataFile.unknown1[2] = 0
DEBUG (BlindWrite5 plugin): dataFile.unknown1[3] = 0
DEBUG (BlindWrite5 plugin): dataFile.offset = 0
DEBUG (BlindWrite5 plugin): dataFile.unknown2[0] = 0
DEBUG (BlindWrite5 plugin): dataFile.unknown2[1] = 0
DEBUG (BlindWrite5 plugin): dataFile.unknown2[2] = 0
DEBUG (BlindWrite5 plugin): dataFile.startLba = -150
DEBUG (BlindWrite5 plugin): dataFile.sectors = 1203
DEBUG (BlindWrite5 plugin): dataFile.filenameLen = 38
DEBUG (BlindWrite5 plugin): dataFile.filename = Sony USB Driver.B6I
DEBUG (BlindWrite5 plugin): dataFile.unknown3 = 0
DEBUG (BlindWrite5 plugin): session[0].filename = 1
DEBUG (BlindWrite5 plugin): session[0].entries = 4
DEBUG (BlindWrite5 plugin): session[0].unknown = 3
DEBUG (BlindWrite5 plugin): session[0].start = -150
DEBUG (BlindWrite5 plugin): session[0].end = 1053
DEBUG (BlindWrite5 plugin): session[0].firstTrack = 1
DEBUG (BlindWrite5 plugin): session[0].lastTrack = 1
DEBUG (BlindWrite5 plugin): session[0].track[0].type = NotData
DEBUG (BlindWrite5 plugin): session[0].track[0].unknown1[0] = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[0].unknown1[1] = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[0].unknown1[2] = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[0].unknown2 = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[0].subchannel = None
DEBUG (BlindWrite5 plugin): session[0].track[0].unknown3 = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[0].ctl = 4
DEBUG (BlindWrite5 plugin): session[0].track[0].adr = 1
DEBUG (BlindWrite5 plugin): session[0].track[0].point = 160
DEBUG (BlindWrite5 plugin): session[0].track[0].unknown4 = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[0].min = 0
DEBUG (BlindWrite5 plugin): session[0].track[0].sec = 0
DEBUG (BlindWrite5 plugin): session[0].track[0].frame = 0
DEBUG (BlindWrite5 plugin): session[0].track[0].zero = 0
DEBUG (BlindWrite5 plugin): session[0].track[0].pmin = 1
DEBUG (BlindWrite5 plugin): session[0].track[0].psec = 0
DEBUG (BlindWrite5 plugin): session[0].track[0].pframe = 0
DEBUG (BlindWrite5 plugin): session[0].track[0].unknown5 = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[0].pregap = 0
DEBUG (BlindWrite5 plugin): session[0].track[0].unknown6[0] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[0].unknown6[1] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[0].unknown6[2] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[0].unknown6[3] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[0].startLba = 0
DEBUG (BlindWrite5 plugin): session[0].track[0].sectors = 0
DEBUG (BlindWrite5 plugin): session[0].track[0].unknown7[0] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[0].unknown7[1] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[0].session = 0
DEBUG (BlindWrite5 plugin): session[0].track[0].unknown8 = 0x0000
DEBUG (BlindWrite5 plugin): session[0].track[1].type = NotData
DEBUG (BlindWrite5 plugin): session[0].track[1].unknown1[0] = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[1].unknown1[1] = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[1].unknown1[2] = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[1].unknown2 = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[1].subchannel = None
DEBUG (BlindWrite5 plugin): session[0].track[1].unknown3 = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[1].ctl = 4
DEBUG (BlindWrite5 plugin): session[0].track[1].adr = 1
DEBUG (BlindWrite5 plugin): session[0].track[1].point = 161
DEBUG (BlindWrite5 plugin): session[0].track[1].unknown4 = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[1].min = 0
DEBUG (BlindWrite5 plugin): session[0].track[1].sec = 0
DEBUG (BlindWrite5 plugin): session[0].track[1].frame = 0
DEBUG (BlindWrite5 plugin): session[0].track[1].zero = 0
DEBUG (BlindWrite5 plugin): session[0].track[1].pmin = 1
DEBUG (BlindWrite5 plugin): session[0].track[1].psec = 0
DEBUG (BlindWrite5 plugin): session[0].track[1].pframe = 0
DEBUG (BlindWrite5 plugin): session[0].track[1].unknown5 = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[1].pregap = 0
DEBUG (BlindWrite5 plugin): session[0].track[1].unknown6[0] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[1].unknown6[1] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[1].unknown6[2] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[1].unknown6[3] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[1].startLba = 0
DEBUG (BlindWrite5 plugin): session[0].track[1].sectors = 0
DEBUG (BlindWrite5 plugin): session[0].track[1].unknown7[0] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[1].unknown7[1] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[1].session = 0
DEBUG (BlindWrite5 plugin): session[0].track[1].unknown8 = 0x0000
DEBUG (BlindWrite5 plugin): session[0].track[2].type = NotData
DEBUG (BlindWrite5 plugin): session[0].track[2].unknown1[0] = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[2].unknown1[1] = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[2].unknown1[2] = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[2].unknown2 = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[2].subchannel = None
DEBUG (BlindWrite5 plugin): session[0].track[2].unknown3 = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[2].ctl = 4
DEBUG (BlindWrite5 plugin): session[0].track[2].adr = 1
DEBUG (BlindWrite5 plugin): session[0].track[2].point = 162
DEBUG (BlindWrite5 plugin): session[0].track[2].unknown4 = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[2].min = 0
DEBUG (BlindWrite5 plugin): session[0].track[2].sec = 0
DEBUG (BlindWrite5 plugin): session[0].track[2].frame = 0
DEBUG (BlindWrite5 plugin): session[0].track[2].zero = 0
DEBUG (BlindWrite5 plugin): session[0].track[2].pmin = 0
DEBUG (BlindWrite5 plugin): session[0].track[2].psec = 16
DEBUG (BlindWrite5 plugin): session[0].track[2].pframe = 3
DEBUG (BlindWrite5 plugin): session[0].track[2].unknown5 = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[2].pregap = 0
DEBUG (BlindWrite5 plugin): session[0].track[2].unknown6[0] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[2].unknown6[1] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[2].unknown6[2] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[2].unknown6[3] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[2].startLba = 0
DEBUG (BlindWrite5 plugin): session[0].track[2].sectors = 0
DEBUG (BlindWrite5 plugin): session[0].track[2].unknown7[0] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[2].unknown7[1] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[2].session = 0
DEBUG (BlindWrite5 plugin): session[0].track[2].unknown8 = 0x0000
DEBUG (BlindWrite5 plugin): session[0].track[3].type = Mode1
DEBUG (BlindWrite5 plugin): session[0].track[3].unknown1[0] = 0x01
DEBUG (BlindWrite5 plugin): session[0].track[3].unknown1[1] = 0x01
DEBUG (BlindWrite5 plugin): session[0].track[3].unknown1[2] = 0x01
DEBUG (BlindWrite5 plugin): session[0].track[3].unknown2 = 0x00000001
DEBUG (BlindWrite5 plugin): session[0].track[3].subchannel = None
DEBUG (BlindWrite5 plugin): session[0].track[3].unknown3 = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[3].ctl = 4
DEBUG (BlindWrite5 plugin): session[0].track[3].adr = 1
DEBUG (BlindWrite5 plugin): session[0].track[3].point = 1
DEBUG (BlindWrite5 plugin): session[0].track[3].unknown4 = 0x00
DEBUG (BlindWrite5 plugin): session[0].track[3].min = 0
DEBUG (BlindWrite5 plugin): session[0].track[3].sec = 0
DEBUG (BlindWrite5 plugin): session[0].track[3].frame = 0
DEBUG (BlindWrite5 plugin): session[0].track[3].zero = 0
DEBUG (BlindWrite5 plugin): session[0].track[3].pmin = 0
DEBUG (BlindWrite5 plugin): session[0].track[3].psec = 2
DEBUG (BlindWrite5 plugin): session[0].track[3].pframe = 0
DEBUG (BlindWrite5 plugin): session[0].track[3].unknown5 = 0x01
DEBUG (BlindWrite5 plugin): session[0].track[3].pregap = 150
DEBUG (BlindWrite5 plugin): session[0].track[3].unknown6[0] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[3].unknown6[1] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[3].unknown6[2] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[3].unknown6[3] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[3].startLba = -150
DEBUG (BlindWrite5 plugin): session[0].track[3].sectors = 1203
DEBUG (BlindWrite5 plugin): session[0].track[3].unknown7[0] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[3].unknown7[1] = 0x00000000
DEBUG (BlindWrite5 plugin): session[0].track[3].session = 1
DEBUG (BlindWrite5 plugin): session[0].track[3].unknown8 = 0x0000
DEBUG (BlindWrite5 plugin): session[0].track[3].unknown9[0] = 0x00000001
DEBUG (BlindWrite5 plugin): session[0].track[3].unknown9[1] = 0x0000041D
DEBUG (BlindWrite5 plugin): Correctly arrived end of image
DEBUG (BlindWrite5 plugin): Building maps
DEBUG (BlindWrite5 plugin): printing track map
DEBUG (BlindWrite5 plugin): Partition sequence: 1
DEBUG (BlindWrite5 plugin):     Partition description: Track 1
DEBUG (BlindWrite5 plugin):     Partition type: CdMode1
DEBUG (BlindWrite5 plugin):     Partition starting sector: 0
DEBUG (BlindWrite5 plugin):     Partition ending sector: 1053
DEBUG (BlindWrite5 plugin): printing partition map
DEBUG (BlindWrite5 plugin): Partition sequence: 1
DEBUG (BlindWrite5 plugin):     Partition name:
DEBUG (BlindWrite5 plugin):     Partition description: Track 1
DEBUG (BlindWrite5 plugin):     Partition type: CdMode1
DEBUG (BlindWrite5 plugin):     Partition starting sector: 0
DEBUG (BlindWrite5 plugin):     Partition sectors: 1053
DEBUG (BlindWrite5 plugin):     Partition starting offset: 0
DEBUG (BlindWrite5 plugin):     Partition size in bytes: 2476656
DEBUG (BlindWrite5 plugin): Rebuilding TOC
DEBUG (BlindWrite5 plugin): TOC len 46
DEBUG (BlindWrite5 plugin): ImageInfo.mediaType = CDROM
DEBUG (Convert-image command): Correctly opened image file.
DEBUG (Convert-image command): Image without headers is 860 bytes.
DEBUG (Convert-image command): Image has 1053 sectors.
DEBUG (Convert-image command): Image identifies media type as CDROM.
Output image format: Aaru Format.
DEBUG (Aaru Format plugin): Got a shift of 12 for 4096 sectors per block
DEBUG (Aaru Format plugin): In memory DDT?: True
Converting media tag SCSI_MODEPAGE_2A
Converting media tag CD_FullTOC
1053 sectors to convert
Converting sectors 1024 to 1054 in track 1 (97.25% done)Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Requested more sectors (1054) than present in track (1053), won't cross tracks (Parameter 'length')
   at Aaru.DiscImages.BlindWrite5.ReadSectorsLong(UInt64 sectorAddress, UInt32 length, UInt32 track) in C:\Users\silas\Desktop\GIT\Aaru\Aaru.Images\BlindWrite5\Read.cs:line 1842
   at Aaru.DiscImages.BlindWrite5.ReadSectorsLong(UInt64 sectorAddress, UInt32 length) in C:\Users\silas\Desktop\GIT\Aaru\Aaru.Images\BlindWrite5\Read.cs:line 1815
   at Aaru.Commands.Image.ConvertImageCommand.Invoke(Boolean verbose, Boolean debug, String cicmXml, String comments, Int32 count, String creator, String driveFirmwareRevision, String driveManufacturer, String driveModel, String driveSerialNumber, Boolean force, String inputPath, Int32 lastMediaSequence, String mediaBarcode, String mediaManufacturer, String mediaModel, String mediaPartNumber, Int32 mediaSequence, String mediaSerialNumber, String mediaTitle, String outputPath, String options, String resumeFile, String format, String geometry, Boolean fixSubchannelPosition, Boolean fixSubchannel, Boolean fixSubchannelCrc, Boolean generateSubchannels) in C:\Users\silas\Desktop\GIT\Aaru\Aaru\Commands\Image\Convert.cs:line 712
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by SilasLaspada** [comment]
Happens with a BWT image too, both of the images are valid because I'm able to extract the files from them using Aaru.
