### ISSUE TITLE
Hashing sectors after dumping CD-i Ready disc crashes Aaru

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#380]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [X] ...in 64-bit

### Description

After dumping a CD-i Ready disc using my MRX-650LE, Aaru crashes at the end of hashing sectors with the error "Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation."

### Exact command line used:

`aaru m dump E: cdiready1.aaruf --first-pregap True --retry-subchannel false`

### Output of command execution with debug output enabled
```
aaru 5.0.99.2991+9a202e02 built by DESKTOP-8B4K7NM in Debug
Copyright c 2011-2020 Natalia Portillo

Output image format: Aaru Format.
Device in database since 7/13/2020 4:03:45 PM.

Checking if drive supports PQ subchannel reading...
Checking if drive supports full raw subchannel reading...
Full raw subchannel reading supported...
Drive returns subchannel in BCD...
Reading full TOC
Building track map...
Calculating pregaps, can take some time...
Track 1 pregap is 0 sectors
Track 2 pregap is 0 sectors
Track 3 pregap is 0 sectors
Track 4 pregap is 0 sectors
Track 5 pregap is 0 sectors
Track 6 pregap is 0 sectors
Track 7 pregap is 0 sectors
Track 8 pregap is 0 sectors
Track 9 pregap is 0 sectors
Track 10 pregap is 0 sectors
Track 11 pregap is 0 sectors
Track 12 pregap is 0 sectors
Reading ATIP
Reading Disc Information
Reading PMA
Reading Session Information
Reading CD-Text from Lead-In
Solving lead-outs...
Detecting disc type...
Disc contains a hidden track...
Checking mode for track 0...
Track 0 is unknown mode 0
Reading first track pregap
Trying to read first track pregap sector -1 (0.000 MiB/sec.)
Got 0 first track pregap sectors.
Reading 16 sectors at a time.
Device reports 292322 blocks (715604256 bytes).
Device can read 16 blocks at a time.
Device reports 2448 bytes per logical block.
SCSI device type: MultiMediaDevice.
Media identified as CDDA.
Setting flags for track 1...
Setting flags for track 2...
Setting flags for track 3...
Setting flags for track 4...
Setting flags for track 5...
Setting flags for track 6...
Setting flags for track 7...
Setting flags for track 8...
Setting flags for track 9...
Setting flags for track 10...
Setting flags for track 11...
Setting flags for track 12...
Track 0 starts at LBA 0 and ends at LBA 153761
Track 1 starts at LBA 153762 and ends at LBA 166146
Track 2 starts at LBA 166147 and ends at LBA 178334
Track 3 starts at LBA 178335 and ends at LBA 192904
Track 4 starts at LBA 192905 and ends at LBA 203871
Track 5 starts at LBA 203872 and ends at LBA 217999
Track 6 starts at LBA 218000 and ends at LBA 229146
Track 7 starts at LBA 229147 and ends at LBA 243066
Track 8 starts at LBA 243067 and ends at LBA 255384
Track 9 starts at LBA 255385 and ends at LBA 270844
Track 10 starts at LBA 270845 and ends at LBA 276694
Track 11 starts at LBA 276695 and ends at LBA 286671
Track 12 starts at LBA 286672 and ends at LBA 292321
Drive reading offset is 24 bytes (6 samples).
Disc offsets is -5476 bytes (-1369 samples)
Setting speed to MAX for data reading.
Setting speed to 8x for audio reading.
Setting index 1 for track 1 to LBA 154109.
Pregap for track 2 set to 145 sectors.
Setting index 1 for track 2 to LBA 166147.
Pregap for track 3 set to 138 sectors.
Setting index 1 for track 3 to LBA 178335.
Pregap for track 4 set to 140 sectors.
Setting index 1 for track 4 to LBA 192905.
Pregap for track 5 set to 140 sectors.
Setting index 1 for track 5 to LBA 203872.
Pregap for track 6 set to 143 sectors.
Setting index 1 for track 6 to LBA 218000.
Pregap for track 7 set to 140 sectors.
Setting index 1 for track 7 to LBA 229147.
Pregap for track 8 set to 142 sectors.
Setting index 1 for track 8 to LBA 243067.
Pregap for track 9 set to 145 sectors.
Setting index 1 for track 9 to LBA 255385.
Pregap for track 10 set to 140 sectors.
Setting index 1 for track 10 to LBA 270845.
Pregap for track 11 set to 140 sectors.
Setting index 1 for track 11 to LBA 276695.
Pregap for track 12 set to 137 sectors.
Setting index 1 for track 12 to LBA 286672.
Reading sector 292307 of 292322 (1.811 MiB/sec.)
Dump finished in 518.2904457 seconds.
Average dump speed 3427.663 KiB/sec.
Average write speed 2273.922 KiB/sec.
Trimming skipped sectors
Setting index 1 for track 1 to LBA 153762.
Trimming sector 154111
Trimming finished in 2.0254877 seconds.
Closing output file.
Closed in 12.6496914 seconds.
Hashing image file...
Hashing image file byte 278921216 of 279036697
Hashing media tags...
Checking filesystems
Hashing tracks...
Hashings sector 153600 of 153762
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Unsupported tag requested (Parameter 'tag')
   at Aaru.DiscImages.AaruFormat.ReadSectorsTag(UInt64 sectorAddress, UInt32 length, SectorTagType tag) in C:\Users\silas\Desktop\GIT\Aaru\Aaru.Images\AaruFormat\Read.cs:line 1515
   at Aaru.DiscImages.AaruFormat.ReadSectorsTag(UInt64 sectorAddress, UInt32 length, UInt32 track, SectorTagType tag) in C:\Users\silas\Desktop\GIT\Aaru\Aaru.Images\AaruFormat\Read.cs:line 1752
   at Aaru.Core.Sidecar.OpticalDisc(IOpticalMediaImage image, Guid filterId, String imagePath, FileInfo fi, PluginBase plugins, List`1 imgChecksums, CICMMetadataType& sidecar, Encoding encoding) in C:\Users\silas\Desktop\GIT\Aaru\Aaru.Core\Sidecar\OpticalDisc.cs:line 689
   at Aaru.Core.Sidecar.Create() in C:\Users\silas\Desktop\GIT\Aaru\Aaru.Core\Sidecar\Sidecar.cs:line 142
   at Aaru.Core.Devices.Dumping.Dump.WriteOpticalSidecar(UInt32 blockSize, UInt64 blocks, MediaType mediaType, LayersType layers, Dictionary`2 mediaTags, Int32 sessions, Double& totalChkDuration, Nullable`1 discOffset) in C:\Users\silas\Desktop\GIT\Aaru\Aaru.Core\Devices\Dumping\Metadata.cs:line 86
   at Aaru.Core.Devices.Dumping.Dump.CompactDisc() in C:\Users\silas\Desktop\GIT\Aaru\Aaru.Core\Devices\Dumping\CompactDisc\Dump.cs:line 1276
   at Aaru.Core.Devices.Dumping.Dump.Mmc() in C:\Users\silas\Desktop\GIT\Aaru\Aaru.Core\Devices\Dumping\MMC.cs:line 201
   at Aaru.Core.Devices.Dumping.Dump.Scsi() in C:\Users\silas\Desktop\GIT\Aaru\Aaru.Core\Devices\Dumping\SCSI.cs:line 238
   at Aaru.Core.Devices.Dumping.Dump.Start() in C:\Users\silas\Desktop\GIT\Aaru\Aaru.Core\Devices\Dumping\Dump.cs:line 223
   at Aaru.Commands.Media.DumpMediaCommand.Invoke(Boolean debug, Boolean verbose, String cicmXml, String devicePath, Boolean resume, String encoding, Boolean firstPregap, Boolean fixOffset, Boolean force, Boolean metadata, Boolean trim, String outputPath, String options, Boolean persistent, UInt16 retryPasses, UInt32 skip, Byte speed, Boolean stopOnError, String format, String subchannel, Boolean private, Boolean fixSubchannelPosition, Boolean retrySubchannel, Boolean fixSubchannel, Boolean fixSubchannelCrc, Boolean generateSubchannels, Boolean skipCdiReadyHole, Boolean eject) in C:\Users\silas\Desktop\GIT\Aaru\Aaru\Commands\Media\Dump.cs:line 632
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by claunia** [comment]
Redump needed.
