### ISSUE TITLE
DVD-R dump fails at sidecar creation

### ISSUE THREAD

**Issue by FakeShemp** [aaru-dps/Aaru#414]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [x] I was running Aaru under Linux [Ubuntu 20.04]...
* [x] ...using .NET Core [3.1]...
* [x] ...in 64-bit

### Description

After dumping a DVD-R to AIF the sidecar creation fails with...

```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Requested more sectors than available (Parameter 'length')
   at Aaru.DiscImages.AaruFormat.ReadSectors(UInt64 sectorAddress, UInt32 length) in /home/rebecca/Documents/CODE/Aaru/Aaru.Images/AaruFormat/Read.cs:line 1479
   at Aaru.DiscImages.AaruFormat.ReadSectorsLong(UInt64 sectorAddress, UInt32 length) in /home/rebecca/Documents/CODE/Aaru/Aaru.Images/AaruFormat/Read.cs:line 1998
   at Aaru.DiscImages.AaruFormat.ReadSectorsLong(UInt64 sectorAddress, UInt32 length, UInt32 track) in /home/rebecca/Documents/CODE/Aaru/Aaru.Images/AaruFormat/Read.cs:line 2144
   at Aaru.Core.Sidecar.OpticalDisc(IOpticalMediaImage image, Guid filterId, String imagePath, FileInfo fi, PluginBase plugins, List`1 imgChecksums, CICMMetadataType& sidecar, Encoding encoding) in /home/rebecca/Documents/CODE/Aaru/Aaru.Core/Sidecar/OpticalDisc.cs:line 602
   at Aaru.Core.Sidecar.Create() in /home/rebecca/Documents/CODE/Aaru/Aaru.Core/Sidecar/Sidecar.cs:line 142
   at Aaru.Core.Devices.Dumping.Dump.WriteOpticalSidecar(UInt32 blockSize, UInt64 blocks, MediaType mediaType, LayersType layers, Dictionary`2 mediaTags, Int32 sessions, Double& totalChkDuration, Nullable`1 discOffset) in /home/rebecca/Documents/CODE/Aaru/Aaru.Core/Devices/Dumping/Metadata.cs:line 86
   at Aaru.Core.Devices.Dumping.Dump.Sbc(Dictionary`2 mediaTags, MediaType dskType, Boolean opticalDisc) in /home/rebecca/Documents/CODE/Aaru/Aaru.Core/Devices/Dumping/SBC.cs:line 1213
   at Aaru.Core.Devices.Dumping.Dump.Mmc() in /home/rebecca/Documents/CODE/Aaru/Aaru.Core/Devices/Dumping/MMC.cs:line 694
   at Aaru.Core.Devices.Dumping.Dump.Scsi() in /home/rebecca/Documents/CODE/Aaru/Aaru.Core/Devices/Dumping/SCSI.cs:line 238
   at Aaru.Core.Devices.Dumping.Dump.Start() in /home/rebecca/Documents/CODE/Aaru/Aaru.Core/Devices/Dumping/Dump.cs:line 223
   at Aaru.Commands.Media.DumpMediaCommand.Invoke(Boolean debug, Boolean verbose, String cicmXml, String devicePath, Boolean resume, String encoding, Boolean firstPregap, Boolean fixOffset, Boolean force, Boolean metadata, Boolean trim, String outputPath, String options, Boolean persistent, UInt16 retryPasses, UInt32 skip, Byte speed, Boolean stopOnError, String format, String subchannel, Boolean private, Boolean fixSubchannelPosition, Boolean retrySubchannel, Boolean fixSubchannel, Boolean fixSubchannelCrc, Boolean generateSubchannels, Boolean skipCdiReadyHole, Boolean eject) in /home/rebecca/Documents/CODE/Aaru/Aaru/Commands/Media/Dump.cs:line 632
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()

```

`m info`

```
Media has 174023 blocks of 2048 bytes/each. (for a total of 339.889 MiB)
PFI:
Disc is a 120mm DVD-R version 5
Disc claims conformation to ECMA-359
Disc maximum transfer rate is unspecified.
Disc has 1 layers
Pitch size is 0,267 μm/bit
Track size is 0,74 μm
Data area starts at PSN 30000h
Data area ends at PSN 5A7C6h
Current Border-Out first sector is PSN 5A7E0h
Next Border-In first sector is PSN 0h

Standard Disc Information:
Disc type declared as CD-DA or CD-ROM
Disc is finalized
Last session is complete
First track on disc is track 1
Disc has 1 sessions
First track in last session is track 1
Last track in last session is track 1
Last session Lead-In address is 0 (as LBA) or 00:00:00
Last possible Lead-Out address is 0 (as LBA) or 00:00:00
Disc is defined for restricted use

Media identified as DVDR
```

### Exact command line used:

`sudo ./aaru m dump --persistent --first-pregap -p 25 /dev/sr0 Cabeza.aaruf`

### Expected behavior:
Dump and sidecar to be created.

### Actual behavior:
Error at sidecar creation.

### If command was expected to work with a device fill this out:

* **Manufacturer**: Asus
* **Model**: BW-16D1HT
* **Bus**:
    * [X] USB

**Comment by claunia** [comment]
Redump needed.

**Comment by FakeShemp** [comment]
Still happens unfortunately...

```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Requested more sectors than available (Parameter 'length')
   at Aaru.DiscImages.AaruFormat.ReadSectors(UInt64 sectorAddress, UInt32 length) in /home/rebecca/Documents/CODE/Aaru/Aaru.Images/AaruFormat/Read.cs:line 1484
   at Aaru.DiscImages.AaruFormat.ReadSectorsLong(UInt64 sectorAddress, UInt32 length) in /home/rebecca/Documents/CODE/Aaru/Aaru.Images/AaruFormat/Read.cs:line 2003
   at Aaru.DiscImages.AaruFormat.ReadSectorsLong(UInt64 sectorAddress, UInt32 length, UInt32 track) in /home/rebecca/Documents/CODE/Aaru/Aaru.Images/AaruFormat/Read.cs:line 2149
   at Aaru.Core.Sidecar.OpticalDisc(IOpticalMediaImage image, Guid filterId, String imagePath, FileInfo fi, PluginBase plugins, List`1 imgChecksums, CICMMetadataType& sidecar, Encoding encoding) in /home/rebecca/Documents/CODE/Aaru/Aaru.Core/Sidecar/OpticalDisc.cs:line 611
   at Aaru.Core.Sidecar.Create() in /home/rebecca/Documents/CODE/Aaru/Aaru.Core/Sidecar/Sidecar.cs:line 142
   at Aaru.Core.Devices.Dumping.Dump.WriteOpticalSidecar(UInt32 blockSize, UInt64 blocks, MediaType mediaType, LayersType layers, Dictionary`2 mediaTags, Int32 sessions, Double& totalChkDuration, Nullable`1 discOffset) in /home/rebecca/Documents/CODE/Aaru/Aaru.Core/Devices/Dumping/Metadata.cs:line 86
   at Aaru.Core.Devices.Dumping.Dump.Sbc(Dictionary`2 mediaTags, MediaType dskType, Boolean opticalDisc) in /home/rebecca/Documents/CODE/Aaru/Aaru.Core/Devices/Dumping/Sbc/Dump.cs:line 871
   at Aaru.Core.Devices.Dumping.Dump.Mmc() in /home/rebecca/Documents/CODE/Aaru/Aaru.Core/Devices/Dumping/MMC.cs:line 697
   at Aaru.Core.Devices.Dumping.Dump.Scsi() in /home/rebecca/Documents/CODE/Aaru/Aaru.Core/Devices/Dumping/SCSI.cs:line 238
   at Aaru.Core.Devices.Dumping.Dump.Start() in /home/rebecca/Documents/CODE/Aaru/Aaru.Core/Devices/Dumping/Dump.cs:line 224
   at Aaru.Commands.Media.DumpMediaCommand.Invoke(Boolean debug, Boolean verbose, String cicmXml, String devicePath, Boolean resume, String encoding, Boolean firstPregap, Boolean fixOffset, Boolean force, Boolean metadata, Boolean trim, String outputPath, String options, Boolean persistent, UInt16 retryPasses, UInt32 skip, Byte speed, Boolean stopOnError, String format, String subchannel, Boolean private, Boolean fixSubchannelPosition, Boolean retrySubchannel, Boolean fixSubchannel, Boolean fixSubchannelCrc, Boolean generateSubchannels, Boolean skipCdiReadyHole, Boolean eject, UInt32 maxBlocks) in /home/rebecca/Documents/CODE/Aaru/Aaru/Commands/Media/Dump.cs:line 646
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```
