### ISSUE TITLE
Crash when aaruremote closes unexpectedly.

### ISSUE THREAD

**Issue by claunia** [aaru-dps/Aaru#416]
```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.                                                                                                             
 ---> System.Net.Sockets.SocketException (32): Broken pipe
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.Socket.Send(Byte[] buffer, SocketFlags socketFlags)
   at Aaru.Devices.Remote.Remote.SendScsiCommand(Byte[] cdb, Byte[]& buffer, Byte[]& senseBuffer, UInt32 timeout, ScsiDirection direction, Double& duration, Boolean& sense) in /home/claunia/Development/Aaru/Aaru/Aaru.Devices/Remote/Remote.cs:line 512
   at Aaru.Devices.Device.SendScsiCommand(Byte[] cdb, Byte[]& buffer, Byte[]& senseBuffer, UInt32 timeout, ScsiDirection direction, Double& duration, Boolean& sense) in /home/claunia/Development/Aaru/Aaru/Aaru.Devices/Device/Commands.cs:line 58
   at Aaru.Devices.Device.Read12(Byte[]& buffer, Byte[]& senseBuffer, Byte rdprotect, Boolean dpo, Boolean fua, Boolean fuaNv, Boolean relAddr, UInt32 lba, UInt32 blockSize, Byte groupNumber, UInt32 transferLength, Boolean streaming, UInt32 timeout, Double& duration) in /home/claunia/Development/Aaru/Aaru/Aaru.Devices/Device/ScsiCommands/SBC.cs:line 210
   at Aaru.Core.Devices.Reader.ScsiReadBlocks(Byte[]& buffer, UInt64 block, UInt32 count, Double& duration) in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/ReaderSCSI.cs:line 608
   at Aaru.Core.Devices.Reader.ReadBlocks(Byte[]& buffer, UInt64 block, UInt32 count, Double& duration) in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Reader.cs:line 147
   at Aaru.Core.Devices.Reader.ReadBlock(Byte[]& buffer, UInt64 block, Double& duration) in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Reader.cs:line 136
   at Aaru.Core.Devices.Dumping.Dump.Sbc(Dictionary`2 mediaTags, MediaType dskType, Boolean opticalDisc) in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/SBC.cs:line 739
   at Aaru.Core.Devices.Dumping.Dump.Scsi() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/SCSI.cs:line 251
   at Aaru.Core.Devices.Dumping.Dump.Start() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/Dump.cs:line 224
   at Aaru.Commands.Media.DumpMediaCommand.Invoke(Boolean debug, Boolean verbose, String cicmXml, String devicePath, Boolean resume, String encoding, Boolean firstPregap, Boolean fixOffset, Boolean force, Boolean metadata, Boolean trim, String outputPath, String options, Boolean persistent, UInt16 retryPasses, UInt32 skip, Byte speed, Boolean stopOnError, String format, String subchannel, Boolean private, Boolean fixSubchannelPosition, Boolean retrySubchannel, Boolean fixSubchannel, Boolean fixSubchannelCrc, Boolean generateSubchannels, Boolean skipCdiReadyHole, Boolean eject, UInt32 maxBlocks) in /home/claunia/Development/Aaru/Aaru/Aaru/Commands/Media/Dump.cs:line 646
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by claunia** [comment]
Move to 6.0, it is not really fixable until exceptions are completely removed from the code.
