### ISSUE TITLE
Exception running media info on XGD

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#471]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [ ] I was running Aaru under Linux [version here]...
* [ ] I was running Aaru under macOS [version here]...
* [ ] ...in 32-bit
* [X] ...in 64-bit
* [ ] ...using an Intel / AMD processor
* [ ] ...using an ARM or Apple Silicon processor
* **Device manufacturer**: TSST
* **Model**: TSSTcorpDVD-ROM SH-D162C
* **Bus**:
    * [] Parallel ATA
    * [ ] Serial ATA
    * [ ] SCSI (any)
    * [ ] ATAPI (mark above if parallel or serial)
    * [ ] USB
      * **USB cable manufacturer**:
      * **USB cable model**:
    * [ ] FireWire
    * [ ] PCMCIA
    * [ ] SecureDigital
      * [ ] Using a USB card reader
          * **USB card reader manufacturer**:
          * **USB card reader model**:
    * [ ] MultiMediaCard
        * [ ] Using a USB card reader
            * **USB card reader manufacturer**:
            * **USB card reader model**:
* [ ] I was dumping media (disk, tape, etc)...
* [ ] I was analyzing media (disk, tape, etc)...
* [ ] I was scanning media (disk, tape, etc)...

### Description

Trying to run media info on an XGD disc crashes Aaru.

### Exact command line used:

`aaru m info E:`

### Output of command execution with debug output enabled
```
aaru 5.2.99.3380-alpha+472a1d94 built by DESKTOP-8B4K7NM in Debug
Copyright c 2011-2021 Natalia Portillo

DEBUG (Media-Info command): --debug=True
DEBUG (Media-Info command): --device=E:
DEBUG (Media-Info command): --output-prefix=
DEBUG (Media-Info command): --verbose=False
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 16.5788 ms.
DEBUG (SCSI Device): INQUIRY took 0.317 ms.
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 13.2968 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 264, Return Type: Single, Sense: False, Last Error: 0) took 2.6962 ms.
DEBUG (SCSI Device): TEST UNIT READY took 0.2794 ms.
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 12.8544 ms.
DEBUG (SCSI Device): INQUIRY took 0.2933 ms.
DEBUG (SCSI Device): MODE SENSE(10) took 0.5216 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 0, Return Type: All, Sense: False, Last Error: 0) took 9.0854 ms.
DEBUG (SCSI Device): KREON GET FEATURE LIST took 0.5141 ms.
DEBUG (SCSI Device): READ CAPACITY took 0.2861 ms.
DEBUG (SCSI Device): READ CAPACITY(16) took 0.6627 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 0, Return Type: Current, Sense: False, Last Error: 0) took 5.6968 ms.
DEBUG (Media-Info command): GET CONFIGURATION current profile is 0010h
DEBUG (Media-Info command): READ DISC STRUCTURE: Recognized Format Layers
SCSI SENSE: ILLEGAL REQUEST
ILLEGAL FIELD IN CDB

DEBUG (Media-Info command): READ DISC STRUCTURE: Write Protection Status
SCSI SENSE: ILLEGAL REQUEST
ILLEGAL FIELD IN CDB

DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: DiscInformation, AGID: 0, Sense: False, Last Error: 0) took 1.6791 ms.
DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: DiscManufacturingInformation, AGID: 0, Sense: False, Last Error: 0) took 1.5119 ms.
DEBUG (Media-Info command): READ MEDIA SERIAL NUMBER
SCSI SENSE: ILLEGAL REQUEST
INVALID COMMAND OPERATION CODE

DEBUG (SCSI Device): INQUIRY took 0.2655 ms.
DEBUG (SCSI Device): KREON EXTRACT SS took 3.9973 ms.
DEBUG (Dump-media command): Getting video partition size
DEBUG (SCSI Device): KREON SET LOCK STATE took 0.5765 ms.
DEBUG (SCSI Device): READ CAPACITY took 0.2775 ms.
DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: DiscInformation, AGID: 0, Sense: False, Last Error: 87) took 0.0094 ms.
DEBUG (Dump-media command): Video partition total size: 6991 sectors
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Aaru.Core.Media.Info.ScsiInfo..ctor(Device dev) in C:\Users\silas\Desktop\GIT\aaru\Aaru.Core\Media\Info\ScsiInfo.cs:line 1313
   at Aaru.Commands.Media.MediaInfoCommand.DoScsiMediaInfo(Boolean debug, String outputPrefix, Device dev) in C:\Users\silas\Desktop\GIT\aaru\Aaru\Commands\Media\Info.cs:line 171
   at Aaru.Commands.Media.MediaInfoCommand.Invoke(Boolean debug, Boolean verbose, String devicePath, String outputPrefix) in C:\Users\silas\Desktop\GIT\aaru\Aaru\Commands\Media\Info.cs:line 153
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Media details

Halo: Combat Evolved

**Comment by SilasLaspada** [comment]
Fixed as of latest commit/
