### ISSUE TITLE
Overflow exception when dumping XGD

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#472]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [ ] I was running Aaru under Linux [version here]...
* [ ] I was running Aaru under macOS [version here]...
* [ ] ...in 32-bit
* [X] ...in 64-bit
* [X] ...using an Intel / AMD processor
* [ ] ...using an ARM or Apple Silicon processor
* **Device manufacturer**: TSST
* **Model**: TSSTcorpDVD-ROM SH-D162C
* **Bus**:
    * [ ] Parallel ATA
    * [ ] Serial ATA
    * [ ] SCSI (any)
    * [ ] ATAPI (mark above if parallel or serial)
    * [ ] USB
      * **USB cable manufacturer**:
      * **USB cable model**:
    * [ ] FireWire
    * [ ] PCMCIA
    * [ ] SecureDigital
      * [ ] Using a USB card reader
          * **USB card reader manufacturer**:
          * **USB card reader model**:
    * [ ] MultiMediaCard
        * [ ] Using a USB card reader
            * **USB card reader manufacturer**:
            * **USB card reader model**:
* [ ] I was dumping media (disk, tape, etc)...
* [ ] I was analyzing media (disk, tape, etc)...
* [ ] I was scanning media (disk, tape, etc)...

### Description

Trying to dump an XGD disc crashes Aaru.

### Exact command line used:

`aaru m dump E: XGD.aaruf`

### Output of command execution with debug output enabled
```
aaru 5.2.99.3380-alpha+472a1d94 built by DESKTOP-8B4K7NM in Debug
Copyright c 2011-2021 Natalia Portillo

DEBUG (Dump-Media command): --cicm-xml=
DEBUG (Dump-Media command): --debug=True
DEBUG (Dump-Media command): --device=E:
DEBUG (Dump-Media command): --encoding=
DEBUG (Dump-Media command): --first-pregap=False
DEBUG (Dump-Media command): --fix-offset=True
DEBUG (Dump-Media command): --force=False
DEBUG (Dump-Media command): --format=
DEBUG (Dump-Media command): --metadata=True
DEBUG (Dump-Media command): --options=
DEBUG (Dump-Media command): --output=XGD.aaruf
DEBUG (Dump-Media command): --persistent=False
DEBUG (Dump-Media command): --resume=True
DEBUG (Dump-Media command): --retry-passes=5
DEBUG (Dump-Media command): --skip=512
DEBUG (Dump-Media command): --stop-on-error=False
DEBUG (Dump-Media command): --trim=True
DEBUG (Dump-Media command): --verbose=False
DEBUG (Dump-Media command): --subchannel=any
DEBUG (Dump-Media command): --private=False
DEBUG (Dump-Media command): --fix-subchannel-position=True
DEBUG (Dump-Media command): --retry-subchannel=True
DEBUG (Dump-Media command): --fix-subchannel=False
DEBUG (Dump-Media command): --fix-subchannel-crc=False
DEBUG (Dump-Media command): --generate-subchannels=False
DEBUG (Dump-Media command): --skip-cdiready-hole=True
DEBUG (Dump-Media command): --eject=False
DEBUG (Dump-Media command): --max-blocks=64
DEBUG (Dump-Media command): --use-buffered-reads=True
DEBUG (Dump-Media command): Parsed options:
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 16.1943 ms.
DEBUG (SCSI Device): INQUIRY took 0.2722 ms.
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 12.8146 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 264, Return Type: Single, Sense: False, Last Error: 0) took 2.6671 ms.
Output image format: Aaru Format.
Device in database since 7/13/2020 4:03:45 PM.
DEBUG (SCSI Device): TEST UNIT READY took 0.2626 ms.

DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 0, Return Type: Current, Sense: False, Last Error: 0) took 5.7023 ms.
DEBUG (SCSI Device): MODE SENSE(10) took 0.5209 ms.
DEBUG (SCSI Device): READ CAPACITY took 0.5272 ms.
DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: DiscInformation, AGID: 0, Sense: False, Last Error: 0) took 1.0569 ms.
PFI:
Disc is a 120mm DVD-ROM version 1
Disc claims conformation to ECMA-267
Disc maximum transfer rate is 10,08 Mbit/sec.
Disc has 2 layers
Layers are in opposite track path
Pitch size is 0,147 µm/bit
Track size is 0,74 µm
Data area starts at PSN 30000h
Data area ends at PSN FCE5EFh
Layer 0 ends at PSN 31AAFh

DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: DiscManufacturingInformation, AGID: 0, Sense: False, Last Error: 0) took 1.0585 ms.
DEBUG (SCSI Device): INQUIRY took 0.2613 ms.
DEBUG (SCSI Device): READ CAPACITY took 0.3292 ms.
DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: DiscInformation, AGID: 0, Sense: False, Last Error: 87) took 0.0097 ms.
Reading Xbox Security Sector.
DEBUG (SCSI Device): KREON EXTRACT SS took 9.0198 ms.
Decoding Xbox Security Sector.
DEBUG (Dump-media command): Getting video partition size
Locking drive.
DEBUG (SCSI Device): KREON SET LOCK STATE took 4.3102 ms.
Getting video partition size.
DEBUG (SCSI Device): READ CAPACITY took 0.2784 ms.
Reading Physical Format Information.
DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: DiscInformation, AGID: 0, Sense: False, Last Error: 87) took 0.0093 ms.
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at Aaru.Core.Devices.Dumping.Dump.Xgd(Dictionary`2 mediaTags, MediaType dskType) in C:\Users\silas\Desktop\GIT\aaru\Aaru.Core\Devices\Dumping\XGD.cs:line 193
   at Aaru.Core.Devices.Dumping.Dump.Mmc() in C:\Users\silas\Desktop\GIT\aaru\Aaru.Core\Devices\Dumping\MMC.cs:line 758
   at Aaru.Core.Devices.Dumping.Dump.Scsi() in C:\Users\silas\Desktop\GIT\aaru\Aaru.Core\Devices\Dumping\SCSI.cs:line 238
   at Aaru.Core.Devices.Dumping.Dump.Start() in C:\Users\silas\Desktop\GIT\aaru\Aaru.Core\Devices\Dumping\Dump.cs:line 232
   at Aaru.Commands.Media.DumpMediaCommand.Invoke(Boolean debug, Boolean verbose, String cicmXml, String devicePath, Boolean resume, String encoding, Boolean firstPregap, Boolean fixOffset, Boolean force, Boolean metadata, Boolean trim, String outputPath, String options, Boolean persistent, UInt16 retryPasses, UInt32 skip, Byte speed, Boolean stopOnError, String format, String subchannel, Boolean private, Boolean fixSubchannelPosition, Boolean retrySubchannel, Boolean fixSubchannel, Boolean fixSubchannelCrc, Boolean generateSubchannels, Boolean skipCdiReadyHole, Boolean eject, UInt32 maxBlocks, Boolean useBufferedReads) in C:\Users\silas\Desktop\GIT\aaru\Aaru\Commands\Media\Dump.cs:line 656
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Media details

Halo: Combat Evolved

**Comment by mnadareski** [comment]
Still occurring after https://github.com/aaru-dps/Aaru/commit/10d286ada607b1749917effcca5ca0a481b6841c

```
 .\aaru.exe --debug media dump --trim false E: XGD.aaruf
aaru 5.2.99.3380-alpha+10d286ad built by REACH in Debug, modified
Copyright c 2011-2021 Natalia Portillo

DEBUG (Dump-Media command): --cicm-xml=
DEBUG (Dump-Media command): --debug=True
DEBUG (Dump-Media command): --device=E:
DEBUG (Dump-Media command): --encoding=
DEBUG (Dump-Media command): --first-pregap=False
DEBUG (Dump-Media command): --fix-offset=True
DEBUG (Dump-Media command): --force=False
DEBUG (Dump-Media command): --format=
DEBUG (Dump-Media command): --metadata=True
DEBUG (Dump-Media command): --options=
DEBUG (Dump-Media command): --output=XGD.aaruf
DEBUG (Dump-Media command): --persistent=False
DEBUG (Dump-Media command): --resume=True
DEBUG (Dump-Media command): --retry-passes=5
DEBUG (Dump-Media command): --skip=512
DEBUG (Dump-Media command): --stop-on-error=False
DEBUG (Dump-Media command): --trim=False
DEBUG (Dump-Media command): --verbose=False
DEBUG (Dump-Media command): --subchannel=any
DEBUG (Dump-Media command): --private=False
DEBUG (Dump-Media command): --fix-subchannel-position=True
DEBUG (Dump-Media command): --retry-subchannel=True
DEBUG (Dump-Media command): --fix-subchannel=False
DEBUG (Dump-Media command): --fix-subchannel-crc=False
DEBUG (Dump-Media command): --generate-subchannels=False
DEBUG (Dump-Media command): --skip-cdiready-hole=True
DEBUG (Dump-Media command): --eject=False
DEBUG (Dump-Media command): --max-blocks=64
DEBUG (Dump-Media command): --use-buffered-reads=True
DEBUG (Dump-Media command): --store-encrypted=True
DEBUG (Dump-Media command): --title-keys=True
DEBUG (Dump-Media command): Parsed options:
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 7.8647 ms.
DEBUG (SCSI Device): INQUIRY took 0.6927 ms.
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 0.721 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 264, Return Type: Single, Sense: False, Last Error: 0) took 5.6982 ms.
Output image format: Aaru Format.
Device not in database, please create a device report and attach it to a Github issue.
DEBUG (SCSI Device): TEST UNIT READY took 6.2182 ms.

DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 0, Return Type: Current, Sense: False, Last Error: 0) took 15.1231 ms.
DEBUG (SCSI Device): MODE SENSE(10) took 1.1823 ms.
DEBUG (SCSI Device): READ CAPACITY took 0.572 ms.
DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: DiscInformation, AGID: 0, Sense: False, Last Error: 0) took 0.9631 ms.
PFI:
Disc is a 120mm DVD-ROM version 1
Disc claims conformation to ECMA-267
Disc maximum transfer rate is 10,08 Mbit/sec.
Disc has 2 layers
Layers are in opposite track path
Pitch size is 0,147 µm/bit
Track size is 0,74 µm
Data area starts at PSN 30000h
Data area ends at PSN FCE5EFh
Layer 0 ends at PSN 31AAFh

DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: DiscManufacturingInformation, AGID: 0, Sense: False, Last Error: 0) took 1.0282 ms.
DEBUG (SCSI Device): INQUIRY took 0.6454 ms.
DEBUG (SCSI Device): READ CAPACITY took 0.5833 ms.
DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: DiscInformation, AGID: 0, Sense: False, Last Error: 87) took 0.0063 ms.
Reading Xbox Security Sector.
DEBUG (SCSI Device): KREON EXTRACT SS took 1694.619 ms.
Decoding Xbox Security Sector.
DEBUG (Dump-media command): Getting video partition size
Locking drive.
DEBUG (SCSI Device): KREON SET LOCK STATE took 1.5796 ms.
Getting video partition size.
DEBUG (SCSI Device): READ CAPACITY took 0.6105 ms.
Reading Physical Format Information.
DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: DiscInformation, AGID: 0, Sense: False, Last Error: 87) took 0.0059 ms.
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at Aaru.Core.Devices.Dumping.Dump.Xgd(Dictionary`2 mediaTags, MediaType dskType) in B:\Programs\GitHub\Aaru\Aaru.Core\Devices\Dumping\XGD.cs:line 194
   at Aaru.Core.Devices.Dumping.Dump.Mmc() in B:\Programs\GitHub\Aaru\Aaru.Core\Devices\Dumping\MMC.cs:line 856
   at Aaru.Core.Devices.Dumping.Dump.Scsi() in B:\Programs\GitHub\Aaru\Aaru.Core\Devices\Dumping\SCSI.cs:line 238
   at Aaru.Core.Devices.Dumping.Dump.Start() in B:\Programs\GitHub\Aaru\Aaru.Core\Devices\Dumping\Dump.cs:line 239
   at Aaru.Commands.Media.DumpMediaCommand.Invoke(Boolean debug, Boolean verbose, String cicmXml, String devicePath, Boolean resume, String encoding, Boolean firstPregap, Boolean fixOffset, Boolean force, Boolean metadata, Boolean trim, String outputPath, String options, Boolean persistent, UInt16 retryPasses, UInt32 skip, Byte speed, Boolean stopOnError, String format, String subchannel, Boolean private, Boolean fixSubchannelPosition, Boolean retrySubchannel, Boolean fixSubchannel, Boolean fixSubchannelCrc, Boolean generateSubchannels, Boolean skipCdiReadyHole, Boolean eject, UInt32 maxBlocks, Boolean useBufferedReads, Boolean storeEncrypted, Boolean titleKeys) in B:\Programs\GitHub\Aaru\Aaru\Commands\Media\Dump.cs:line 680
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
Uploading statistics
```

**Comment by mnadareski** [comment]
This happens both with and without admin privileges.
The device is a SH-D163B connected via SATA directly to the motherboard. Not over USB.
