### ISSUE TITLE
[HD-Copy] Test images not recognized.

### ISSUE THREAD

**Issue by claunia** [aaru-dps/Aaru#557]
### Prerequisites

* [x] Are you running the latest version?
* [x] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [x] I was running Aaru under Linux 5.10.16-arch1-1...
* [x] ...in 64-bit
* [x] ...using an Intel / AMD processor
    * **Image format**:  HD-Copy
    * **Application that created the image**:  HD-Copy
* [x] I was checksumming the image

### Description

Test images not recognized.

### Exact command line used:

Unit tests.

### Expected behavior:
HD-Copy images opens correctly.

### Actual behavior:
HD-Copy images raise an exception.

### Output of command execution with debug output enabled
```
System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at Aaru.DiscImages.HdCopy.Open(IFilter imageFilter) in /home/claunia/Development/Aaru/Aaru/Aaru.Images/HDCopy/Read.cs:line 82
   at Aaru.Tests.Images.HDCopy.<Hashes>b__8_0() in /home/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/HDCopy.cs:line 1196
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.HDCopy.Hashes() in /home/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/HDCopy.cs:line 1188
   
```

**Comment by darkstar** [comment]
These files are a different variant of the HD Copy format than what I initially implemented. Looks like they have a 14-byte header with the name of the disk in it. The regular file header starts at offset 0x0e... Will take a look
