### ISSUE TITLE
[ImageDisk] Invalid sector type when reading XDF image.

### ISSUE THREAD

**Issue by claunia** [aaru-dps/Aaru#558]
### Prerequisites

* [x] Are you running the latest version?
* [x] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [x] I was running Aaru under Linux 5.10.16-arch1-1...
* [x] ...in 64-bit
* [x] ...using an Intel / AMD processor
    * **Image format**:  ImageDisk
    * **Application that created the image**:  HxC
* [x] I was checksumming the image

### Description

Invalid sector type when reading XDF image.

### Exact command line used:

Unit tests.

### Expected behavior:
Image opens correctly.

### Actual behavior:
Invalid sector type.

### Output of command execution with debug output enabled
```
Aaru.CommonTypes.Exceptions.ImageNotSupportedException : Invalid sector type 119
   at Aaru.DiscImages.Imd.Open(IFilter imageFilter) in /home/claunia/Development/Aaru/Aaru/Aaru.Images/IMD/Read.cs:line 162
   at Aaru.Tests.Images.HxC.ImageDisk.<Hashes>b__8_0() in /home/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/HxC/ImageDisk.cs:line 428
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.HxC.ImageDisk.Hashes() in /home/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/HxC/ImageDisk.cs:line 420
```

**Comment by claunia** [comment]
As of ce353d688420387c32de1172885e9c86b7327c3c all unit tests pass, image is readable, convertible and shows filesystem info correctly.
