### ISSUE TITLE
Exception when running aaru from within mintty (MSYS shell)

### ISSUE THREAD

**Issue by darkstar** [aaru-dps/Aaru#562]
### Prerequisites

* [x] Are you running the latest version?
* [x] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [x] I was running Aaru under Windows 10...
* [ ] I was running Aaru under Linux [version here]...
* [ ] I was running Aaru under macOS [version here]...
* [ ] ...in 32-bit
* [x] ...in 64-bit
* [x] ...using an Intel / AMD processor
* [ ] ...using an ARM or Apple Silicon processor

### Description

When  running aaru from within a mintty shell (like from "Git for Windows" or MinGW/MSYS2), during initial configuration, the following exception occurs:

````
...
Do you want to enable the decryption of copy protected media (also known as DRM),
like for example DVD Video CSS encryption.
Consult your local laws before enabling it, as this is illegal in some countries, or
only legal under some circumstances.
Do you want to decryption of copy protected media? (Y/N): Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at System.Console.ReadKey()
   at Aaru.Commands.ConfigureCommand.Invoke(Boolean debug, Boolean verbose) in D:\Devel\Aaru\Aaru\Commands\Configure.cs:line 105
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
...
````

Presumably, because mintty does funny things with the console

### Exact command line used:

````
user@laptop MINGW64 /d/Devel/Aaru (master)
$ Aaru/bin/Debug/netcoreapp3.1/aaru
````

### Expected behavior:
Either a working console input, or a user-readable error that initial interactive configuration is not possible through alternative shells. In that case, providing command-line parameters like `--accept-gdpr-foo=yes` for each question would be useful.

### Actual behavior:
exception is thrown as seen above

**Comment by claunia** [comment]
Considering it works in other alternative shells like Powershell and Windows Terminal it looks like it is a bug in mintty and/or dotnet, we cannot fix it here.
