### ISSUE TITLE
[CPCDSK] Exception trying to open image created by z88dk

### ISSUE THREAD

**Issue by claunia** [aaru-dps/Aaru#587]
### Prerequisites

* [x] Are you running the latest version?
* [x] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [x] I was running Aaru under Linux 5.11.4-arch1-1...
* [x] ...in 64-bit
* [x] ...using an Intel / AMD processor
    * **Image format**:  Extended CPCDSK
    * **Application that created the image**: z88dk
* [x] I was listing the filesystem contents...

### Description
Exception trying to open CPCDSK image created by z88dk

### Exact command line used:
Unit test.

### Expected behavior:
Image recognized properly.

### Actual behavior:
System.IndexOutOfRangeException

### Output of command execution with debug output enabled
```
System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at Aaru.DiscImages.Cpcdsk.Open(IFilter imageFilter) in /home/claunia/Development/Aaru/Aaru/Aaru.Images/CPCDSK/Read.cs:line 205
   at Aaru.Tests.Filesystems.FilesystemTest.<Detect>b__11_0() in /home/claunia/Development/Aaru/Aaru/Aaru.Tests/Filesystems/FilesystemTest.cs:line 53
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Filesystems.FilesystemTest.Detect() in /home/claunia/Development/Aaru/Aaru/Aaru.Tests/Filesystems/FilesystemTest.cs:line 30
```

### Image
Unit tests.

**Comment by claunia** [comment]
Fixed in 140a9380f908a3294c2ce186f5e354426860fe4e.
