### ISSUE TITLE
Unable to read medium - TDK DVD-R

### ISSUE THREAD

**Issue by robin-francois** [aaru-dps/Aaru#588]
### Prerequisites

* [x] Are you running the latest version?
* [ ] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [x] I was running Aaru under Linux aaru 5.2.99.3380-alpha+f50a9b2a...
* [x] ...in 64-bit
* [x] ...using an Intel / AMD processor
* **Device manufacturer**: ASUS
* **Model**: BW-16D1HT
* **Bus**: 
    * [x] Serial ATA
* [x] I was dumping/analyzing/scanning DVD-R Single Sided x16, brand TDK

### Description

Trying to preserve on a batch of around 40 TDK Single Sided x16 DVD-R. Sampled 5 media, all have been reported unreadable by various drives.

Most of media commands would stop with `Unable to read medium`. Any dump attempts fails.

Cannot exclude that oxidation/natural degradation, bad writing/burning or bad media quality have made the media complety unreadable. Just want to exclude any other causes.

### Exact command line used:

`aaru -d m info /dev/sr0`

but also

`aaru m dump /dev/sr0`

### Expected behavior:
Media dumps.

### Actual behavior:
Dumping fails with `Unable to read medium`.

### Output of command execution with debug output enabled
<details>
<summary>aaru -d m info /dev/sr0</summary>

```
aaru -d m info /dev/sr0
aaru 5.2.99.3380-alpha+f50a9b2a built by pcw-pz-extra01 in Release, modified
Copyright © 2011-2021 Natalia Portillo

DEBUG (Media-Info command): --debug=True
DEBUG (Media-Info command): --device=/dev/sr0
DEBUG (Media-Info command): --output-prefix=
DEBUG (Media-Info command): --verbose=False
DEBUG (SCSI Device): INQUIRY took 0,1298 ms.
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 0,016 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 264, Return Type: Single, Sense: False, Last Error: 0) took 0,3713 ms.
DEBUG (SCSI Device): TEST UNIT READY took 0,353 ms.
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 0,0094 ms.
Error 14 querying ATA PACKET IDENTIFY
DEBUG (SCSI Device): INQUIRY took 0,1984 ms.
DEBUG (SCSI Device): MODE SENSE(10) took 0,6234 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 0, Return Type: All, Sense: False, Last Error: 0) took 1 ms.
DEBUG (SCSI Device): REPORT ASF (AGID: 0, Sense: False, Last Error: 0) took 0,2373 ms.
DEBUG (SCSI Device): READ CAPACITY took 1 ms.
DEBUG (SCSI Device): READ CAPACITY(16) took 0,0463 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 0, Return Type: Current, Sense: False, Last Error: 0) took 1 ms.
DEBUG (Media-Info command): GET CONFIGURATION current profile is 0011h
DEBUG (Media-Info command): READ DISC STRUCTURE: Recognized Format Layers
SCSI SENSE: ILLEGAL REQUEST
ILLEGAL FIELD IN CDB

DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: WriteProtectionStatus, AGID: 0, Sense: False, Last Error: 0) took 0,2904 ms.
DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: DiscInformation, AGID: 0, Sense: False, Last Error: 0) took 0,5047 ms.
DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: DiscManufacturingInformation, AGID: 0, Sense: False, Last Error: 0) took 0,2432 ms.
DEBUG (Media-Info command): READ DISC STRUCTURE: Last-Out Border RMD
SCSI SENSE: ILLEGAL REQUEST
ILLEGAL FIELD IN CDB

DEBUG (SCSI Device): INVALIDATE AGID (AGID: 0, Sense: False, Last Error: 0) took 1 ms.
DEBUG (SCSI Device): REPORT AGID CSS/CPPM (AGID: 0, Sense: False, Last Error: 0) took 1 ms.
DEBUG (SCSI Device): SEND CHALLENGE (AGID: 3, Challenge System.Byte[], Sense: False, Last Error: 0) took 1 ms.
DEBUG (SCSI Device): REPORT KEY1 (AGID: 3, Sense: False, Last Error: 0) took 0,4253 ms.
DEBUG (SCSI Device): REPORT CHALLENGE (AGID: 3, Sense: False, Last Error: 0) took 1 ms.
DEBUG (SCSI Device): SEND CHALLENGE (AGID: 3, KEY2 System.Byte[], Sense: False, Last Error: 0) took 1 ms.
DEBUG (Media-Info command): READ DISC STRUCTURE: Disc Key
SCSI SENSE: ILLEGAL REQUEST
ILLEGAL FIELD IN CDB

DEBUG (Media-Info command): READ DISC STRUCTURE: Sector CMI
SCSI SENSE: ILLEGAL REQUEST
LOGICAL BLOCK ADDRESS OUT OF RANGE

DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: PreRecordedInfo, AGID: 0, Sense: False, Last Error: 0) took 1 ms.
DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: DvdrMediaIdentifier, AGID: 0, Sense: False, Last Error: 0) took 0,1702 ms.
DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: DvdrPhysicalInformation, AGID: 0, Sense: False, Last Error: 0) took 33 ms.
DEBUG (SCSI Device): READ MEDIA SERIAL NUMBER took 0,0023 ms.
DEBUG (SCSI Device): READ DISC INFORMATION (Data Type: DiscInformation, Sense: False, Last Error: 0) took 0,4556 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 0, Return Type: Current, Sense: False, Last Error: 0) took 1 ms.
DEBUG (Media-Info command): GET CONFIGURATION current profile is 0011h
DEBUG (SCSI Device): READ CD (LBA: 0, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: True, Last Error: 0) took 11 ms.
DEBUG (SCSI Device): READ CD (LBA: 0, Block Size: 2352, Transfer Length: 1, Expected Sector Type: Cdda, DAP: False, Relative Address: False, Sync: False, Headers: None, User Data: True, ECC/EDC: False, C2: None, Subchannel: None, Sense: True, Last Error: 0) took 10 ms.
PFI:
Disc is a 120mm DVD-R version 5
Disc claims conformation to ECMA-359
Disc maximum transfer rate is unspecified.
Disc has 1 layers
Pitch size is 0,267 μm/bit
Track size is 0,74 μm
Data area starts at PSN 30000h
Data area ends at PSN 26127Fh
Current Border-Out first sector is PSN 2FE10h
Next Border-In first sector is PSN 2FFA0h

Standard Disc Information:
Disc type declared as CD-DA or CD-ROM
Disc is incomplete
Last session is incomplete
First track on disc is track 1
Disc has 1 sessions
First track in last session is track 1
Last track in last session is track 5
Last session Lead-In address is 0 (as LBA) or 00:00:00
Last possible Lead-Out address is 0 (as LBA) or 00:00:00
Disc is defined for unrestricted use

Media Serial Number:
Media identified as DVDR
DEBUG (Submit stats): Uploading statistics
```
</details>

<details>
<summary>dmesg output</summary>

```
[2420381.046085] sr 3:0:0:0: [sr0] tag#29 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE cmd_age=0s
[2420381.046091] sr 3:0:0:0: [sr0] tag#29 Sense Key : Illegal Request [current]
[2420381.046096] sr 3:0:0:0: [sr0] tag#29 Add. Sense: Logical block address out of range
[2420381.046100] sr 3:0:0:0: [sr0] tag#29 CDB: Read(10) 28 00 00 00 00 01 00 00 01 00
[2420381.046103] blk_update_request: I/O error, dev sr0, sector 4
[2420381.046107] Buffer I/O error on dev sr0, logical block 1, async page read
```
</details>

### Media details
Two pictures of one of sampled media and binary output attached.
![DSC_1515](https://user-images.githubusercontent.com/1881151/120082727-d2f00380-c0c4-11eb-999f-34c34a519ac1.JPG)

![DSC_1517](https://user-images.githubusercontent.com/1881151/120082723-ce2b4f80-c0c4-11eb-9930-c9a2ce928a80.JPG)

[whatever_debug.zip](https://github.com/aaru-dps/Aaru/files/6565240/whatever_debug.zip)

**Comment by robin-francois** [comment]
With additional investigations, media can be dumped with `ddrescue` with very minor issues at the end of the media.

Investigations with @SilasLaspada and @claunia seems to point to DVD VR media, based on `media info` or `media scan`:

```aaru m info /dev/sr0 
aaru 5.2.99.3380-alpha+1ee69230 built by pcw-pz-extra01 in Release, modified
Copyright © 2011-2021 Natalia Portillo

PFI:
Disc is a 120mm DVD-R version 5
Disc claims conformation to ECMA-359
Disc maximum transfer rate is unspecified.
Disc has 1 layers
Pitch size is 0,267 μm/bit
Track size is 0,74 μm
Data area starts at PSN 30000h
Data area ends at PSN 26127Fh
Current Border-Out first sector is PSN 2FE10h
Next Border-In first sector is PSN 2FFA0h

Standard Disc Information:
Disc type declared as CD-DA or CD-ROM
Disc is incomplete
Last session is incomplete
First track on disc is track 1
Disc has 1 sessions
First track in last session is track 1
Last track in last session is track 26
Last session Lead-In address is 0 (as LBA) or 00:00:00
Last possible Lead-Out address is 0 (as LBA) or 00:00:00
Disc is defined for unrestricted use

Media Serial Number: 545448303200000000000000
Media identified as DVDR
```

```aaru m scan /dev/sr0 
aaru 5.2.99.3380-alpha+1ee69230 built by pcw-pz-extra01 in Release, modified
Copyright © 2011-2021 Natalia Portillo

Unable to read medium.
Took a total of 0 seconds (0 processing commands).
Average speed: 0,000 MiB/sec.
Fastest speed burst: 0,000 MiB/sec.
Slowest speed burst: 0,000 MiB/sec.
Summary:
0 sectors took less than 3 ms.
0 sectors took less than 10 ms but more than 3 ms.
0 sectors took less than 50 ms but more than 10 ms.
0 sectors took less than 150 ms but more than 50 ms.
0 sectors took less than 500 ms but more than 150 ms.
0 sectors took more than 500 ms.
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Aaru.Commands.Media.MediaScanCommand.Invoke(Boolean debug, Boolean verbose, String devicePath, String ibgLog, String mhddLog, Boolean useBufferedReads)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   [...]
```

Some interesting strings extracted from the dump of the media with `ddrescue`:
```$ strings -n 10 test.test | grep -i "dvd"
DVDVIDEO-VTS
DVDVIDEO-VTS
DVD_RTR_VMG0
dvdvrx010BC11-----USANL
dvdvrx010BR200610281624E
dvdvrx010panasonic0100103E01
cdvdvrx0010001001010
dvdvrx010panasonic0100103E01
DVDVIDEO-VTS
DVDVIDEO-VTS
DVD_RTR_VMG0
dvdvrx010BC11-----USANL
dvdvrx010BR200610281624E
dvdvrx010BC11-----USANL
[...]
```

**Comment by robin-francois** [comment]
For a finalised media coming from the same Panasonic machine

```
/home/Extraction/aaru-latest/aaru i info *.aaru
aaru 5.2.99.3380-alpha+1ee69230 built by pcw-pz-extra01 in Release, modified
Copyright © 2011-2021 Natalia Portillo

Image format identified by Aaru Format (49360069-1784-4a2f-b723-0c844d610b0a).

Image information:
Format: Aaru version 1.0
Was created with Aaru version 5.2
Image without headers is 1117066894 bytes long
Contains a media of 745760 sectors with a maximum sector size of 2048 bytes (if all sectors are of the same size this would be 1527316480 bytes)
Created on 7/5/2021 8:10:44 AM
Last modified on 7/5/2021 8:22:37 AM
Contains a media of type DVDROM and XML type OpticalDisc
Has partitions
Has sessions
Contains 5 readable media tags:
DVD_PFI DVD_DMI DVDR_PreRecordedInfo DVDR_MediaIdentifier DVDR_PFI

DVD Physical Format Information contained in image:
Disc is a 120mm DVD-R version 5
Disc claims conformation to ECMA-359
Disc maximum transfer rate is unspecified.
Disc has 1 layers
Pitch size is 0,267 μm/bit
Track size is 0,74 μm
Data area starts at PSN 30000h
Data area ends at PSN E611Fh
Current Border-Out first sector is PSN E6130h
Next Border-In first sector is PSN EF4D0h

DVD-R Physical Format Information contained in image:
Disc is a 120mm DVD-R version 5
Disc claims conformation to ECMA-359
Disc maximum transfer rate is unspecified.
Disc has 1 layers
Pitch size is 0,267 μm/bit
Track size is 0,74 μm
Data area starts at PSN 30000h
Data area ends at PSN 26127Fh
Current Border-Out first sector is PSN 2FE10h
Next Border-In first sector is PSN 2FFA0h

Image sessions:
Session  First track  Last track  Start       End
=========================================================
1        1            12          0           745759

Image tracks:
Track  Type             Bps   Raw bps Subchannel  Pregap  Start       End
=================================================================================
1      Data             2048  2048    None        0       0           1519
2      Data             2048  2048    None        0       1536        1775
3      Data             2048  2048    None        0       1792        47551
4      Data             2048  2048    None        0       47568       47599
5      Data             2048  2048    None        0       47616       47855
6      Data             2048  2048    None        0       47872       205967
7      Data             2048  2048    None        0       205984      206031
8      Data             2048  2048    None        0       206048      206287
9      Data             2048  2048    None        0       206304      745567
10     Data             2048  2048    None        0       745584      745647
11     Data             2048  2048    None        0       745664      745727
12     Data             2048  2048    None        0       745744      745759

Track indexes:
Track  Index  Start
=======================

Dump hardware information:
Manufacturer  Model      Serial       Software  Version      Operating system  Start     End      
===================================================================================================
ASUS          BW-16D1HT  KLOK7S85353  Aaru      5.2.99.3380  Linux             0         745759   
```

```
$ /home/Extraction/aaru-latest/aaru fs info *.aaru
aaru 5.2.99.3380-alpha+1ee69230 built by pcw-pz-extra01 in Release, modified
Copyright © 2011-2021 Natalia Portillo

Image format identified by Aaru Format.

12 partitions found.

Partition 0:
Partition name: Track 1
Partition type: Data
Partition start: sector 0, byte 0
Partition length: 1520 sectors, 0 bytes
Partition scheme: Optical disc track
Partition description:

Identifying filesystem on partition
Identified by 2 plugins
As identified by ISO9660 Filesystem.
ISO9660 file system
------------------------------
VOLUME DESCRIPTOR INFORMATION:
------------------------------
System identifier:
Volume identifier: DVD_VIDEO_RECORDER
Volume set identifier: DVD_VIDEO_RECORDER
Publisher identifier:
Data preparer identifier:
Application identifier:
Volume creation date: 8/2/2010 7:07:45 PM
Volume has not been modified.
Volume does not expire.
Volume has always been effective.
Volume has 745760 blocks of 2048 bytes each
As identified by Universal Disk Format.
Universal Disk Format
Volume is number 1 of 1
Volume set identifier: 3d02a0f6DVD_UDF DVD_VIDEO_RECORDER
Volume name: DVD_VIDEO_RECORDER
Volume uses 2048 bytes per block
Volume was last written in 8/2/2010 8:07:45 PM
Volume contains 1 partitions
Volume contains 13 files and 2 directories
Volume conforms to *OSTA UDF Compliant
Volume was last written by: *MEI_VED
Volume requires UDF version 1.02 to be read
Volume requires UDF version 1.02 to be written to
Volume cannot be written by any UDF version higher than 1.02

Partition 1:
Partition name: Track 2
Partition type: Data
Partition start: sector 1536, byte 0
Partition length: 240 sectors, 0 bytes
Partition scheme: Optical disc track
Partition description:

Identifying filesystem on partition
Filesystem not identified

Partition 2:
Partition name: Track 3
Partition type: Data
Partition start: sector 1792, byte 0
Partition length: 45760 sectors, 0 bytes
Partition scheme: Optical disc track
Partition description:

Identifying filesystem on partition
Filesystem not identified

Partition 3:
Partition name: Track 4
Partition type: Data
Partition start: sector 47568, byte 0
Partition length: 32 sectors, 0 bytes
Partition scheme: Optical disc track
Partition description:

Identifying filesystem on partition
Filesystem not identified

Partition 4:
Partition name: Track 5
Partition type: Data
Partition start: sector 47616, byte 0
Partition length: 240 sectors, 0 bytes
Partition scheme: Optical disc track
Partition description:

Identifying filesystem on partition
Filesystem not identified

Partition 5:
Partition name: Track 6
Partition type: Data
Partition start: sector 47872, byte 0
Partition length: 158096 sectors, 0 bytes
Partition scheme: Optical disc track
Partition description:

Identifying filesystem on partition
Filesystem not identified

Partition 6:
Partition name: Track 7
Partition type: Data
Partition start: sector 205984, byte 0
Partition length: 48 sectors, 0 bytes
Partition scheme: Optical disc track
Partition description:

Identifying filesystem on partition
Filesystem not identified

Partition 7:
Partition name: Track 8
Partition type: Data
Partition start: sector 206048, byte 0
Partition length: 240 sectors, 0 bytes
Partition scheme: Optical disc track
Partition description:

Identifying filesystem on partition
Filesystem not identified

Partition 8:
Partition name: Track 9
Partition type: Data
Partition start: sector 206304, byte 0
Partition length: 539264 sectors, 0 bytes
Partition scheme: Optical disc track
Partition description:

Identifying filesystem on partition
Filesystem not identified

Partition 9:
Partition name: Track 10
Partition type: Data
Partition start: sector 745584, byte 0
Partition length: 64 sectors, 0 bytes
Partition scheme: Optical disc track
Partition description:

Identifying filesystem on partition
Filesystem not identified

Partition 10:
Partition name: Track 11
Partition type: Data
Partition start: sector 745664, byte 0
Partition length: 64 sectors, 0 bytes
Partition scheme: Optical disc track
Partition description:

Identifying filesystem on partition
Filesystem not identified

Partition 11:
Partition name: Track 12
Partition type: Data
Partition start: sector 745744, byte 0
Partition length: 16 sectors, 0 bytes
Partition scheme: Optical disc track
Partition description:

Identifying filesystem on partition
Filesystem not identified
```


```
$ /home/Extraction/aaru-latest/aaru fs ls *.aaru
aaru 5.2.99.3380-alpha+1ee69230 built by pcw-pz-extra01 in Release, modified
Copyright © 2011-2021 Natalia Portillo

Image format identified by Aaru Format.
12 partitions found.

Partition 0:
Identifying filesystem on partition
Identified by 2 plugins
As identified by ISO9660 Filesystem.
Root directory
                         <DIR>                 VIDEO_TS

Directory: VIDEO_TS
                            608        14,336  VIDEO_TS.IFO
                            688        14,336  VIDEO_TS.BUP
                            656        38,912  VIDEO_TS.VOB
                           1536        16,384  VTS_01_0.IFO
                          47536        16,384  VTS_01_0.BUP
                           1792    93,624,320  VTS_01_1.VOB
                          47616        47,104  VTS_02_0.IFO
                         205936        47,104  VTS_02_0.BUP
                          47872   323,659,776  VTS_02_1.VOB
                         206048        51,200  VTS_03_0.IFO
                         745536        51,200  VTS_03_0.BUP
                         206304 1,073,170,432  VTS_03_1.VOB
                         730313    31,131,648  VTS_03_2.VOB


Partition 1:
Identifying filesystem on partition
Filesystem not identified

Partition 2:
Identifying filesystem on partition
Filesystem not identified

Partition 3:
Identifying filesystem on partition
Filesystem not identified

Partition 4:
Identifying filesystem on partition
Filesystem not identified

Partition 5:
Identifying filesystem on partition
Filesystem not identified

Partition 6:
Identifying filesystem on partition
Filesystem not identified

Partition 7:
Identifying filesystem on partition
Filesystem not identified

Partition 8:
Identifying filesystem on partition
Filesystem not identified

Partition 9:
Identifying filesystem on partition
Filesystem not identified

Partition 10:
Identifying filesystem on partition
Filesystem not identified

Partition 11:
Identifying filesystem on partition
Filesystem not identified
```

**Comment by robin-francois** [comment]
I did manage to get my hands on the original hardware used to make the DVDs: a Panasonic DVD Video Recorder DMR-HS2. I was able to finalise the DVDs.

Here is an `aaru compare` between a `dd` RAW image (renamed to .iso) of an unfinalised DVD AND a `aaru dump` of the same finalised DVD:
````
$  /home/Extraction/aaru-latest/aaru i compare finalised.aaru unfinalised.iso
aaru 5.2.99.3380-alpha+d5a43f6c built by pcw-pz-extra01 in Release, modified
Copyright © 2011-2021 Natalia Portillo

Input file 1 format identified by Aaru Format.
Input file 2 format identified by Raw Disk Image.
Comparing disk image characteristics
Comparing sectors...
Comparing sector 1276159 of 1276159...
Disc image 1: finalised.aaru
Disc image 2: unfinalised.iso
Image sectors differ
Disk type differ
Image 1 has more sectors
Sector 16 is different
Sector 17 is different
Sector 18 is different
Sector 19 is different
Sector 20 is different
Sector 32 is different
Sector 33 is different
Sector 34 is different
Sector 35 is different
Sector 36 is different
Sector 37 is different
Sector 48 is different
Sector 49 is different
Sector 50 is different
Sector 51 is different
Sector 52 is different
Sector 53 is different
Sector 64 is different
Sector 65 is different
Sector 256 is different
Sector 257 is different
Sector 258 is different
Sector 259 is different
Sector 260 is different
Sector 272 is different
Sector 273 is different
Sector 274 is different
Sector 275 is different
Sector 276 is different
Sector 277 is different
Sector 285 is different
Sector 286 is different
Sector 287 is different
Sector 288 is different
Sector 289 is different
Sector 290 is different
Sector 291 is different
Sector 292 is different
Sector 293 is different
Sector 294 is different
Sector 295 is different
Sector 296 is different
Sector 297 is different
Sector 298 is different
Sector 299 is different
Sector 300 is different
Sector 301 is different
Sector 302 is different
Sector 303 is different
Sector 304 is different
Sector 305 is different
Sector 608 is different
Sector 609 is different
Sector 610 is different
Sector 611 is different
Sector 612 is different
Sector 613 is different
Sector 614 is different
Sector 656 is different
Sector 657 is different
Sector 658 is different
Sector 659 is different
Sector 660 is different
Sector 661 is different
Sector 662 is different
Sector 663 is different
Sector 664 is different
Sector 665 is different
Sector 666 is different
Sector 667 is different
Sector 668 is different
Sector 669 is different
Sector 670 is different
Sector 671 is different
Sector 672 is different
Sector 673 is different
Sector 674 is different
Sector 688 is different
Sector 689 is different
Sector 690 is different
Sector 691 is different
Sector 692 is different
Sector 693 is different
Sector 694 is different
Images differ
```
