### ISSUE TITLE
Converting ISO to MDF with `--generate-subchannels` crashes Aaru

### ISSUE THREAD

**Issue by darkstar** [aaru-dps/Aaru#589]
### Prerequisites

* [x] Are you running the latest version?
* [x] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [x] I was running Aaru under Windows 7...
* [ ] I was running Aaru under Linux [version here]...
* [ ] I was running Aaru under macOS [version here]...
* [ ] ...in 32-bit
* [x] ...in 64-bit
* [x] ...using an Intel / AMD processor
* [ ] ...using an ARM or Apple Silicon processor

### Description

Aaru crashes when converting ISO to MDS+MDF and using the `--generate-subchannels` flag

### Exact command line used:

````
aaru --debug image convert ALFONS.iso test.mds --generate-subchannels
```` 

### Expected behavior:
No crash

### Actual behavior:
Crash

### Output of command execution with debug output enabled
```
j:\>aaru --debug image convert ALFONS.iso test.mds --generate-subchannels
aaru 5.2.99.3380-alpha+7ddd336a built by APPVEYOR-VM in Debug
Copyright © 2011-2021 Natalia Portillo

DEBUG (Image convert command): --cicm-xml=
DEBUG (Image convert command): --comments=
DEBUG (Image convert command): --count=64
DEBUG (Image convert command): --creator=
DEBUG (Image convert command): --debug=True
DEBUG (Image convert command): --drive-manufacturer=
DEBUG (Image convert command): --drive-model=
DEBUG (Image convert command): --drive-revision=
DEBUG (Image convert command): --drive-serial=
DEBUG (Image convert command): --force=False
DEBUG (Image convert command): --format=
DEBUG (Image convert command): --geometry=
DEBUG (Image convert command): --input=ALFONS.iso
DEBUG (Image convert command): --media-barcode=
DEBUG (Image convert command): --media-lastsequence=0
DEBUG (Image convert command): --media-manufacturer=
DEBUG (Image convert command): --media-model=
DEBUG (Image convert command): --media-partnumber=
DEBUG (Image convert command): --media-sequence=0
DEBUG (Image convert command): --media-serial=
DEBUG (Image convert command): --media-title=
DEBUG (Image convert command): --options=
DEBUG (Image convert command): --output=test.mds
DEBUG (Image convert command): --resume-file=
DEBUG (Image convert command): --verbose=False
DEBUG (Image convert command): --fix-subchannel-position=True
DEBUG (Image convert command): --fix-subchannel=False
DEBUG (Image convert command): --fix-subchannel-crc=False
DEBUG (Image convert command): --generate-subchannels=True
DEBUG (Image convert command): Parsed options:
DEBUG (Format detection): Trying plugin Aaru Format
DEBUG (Format detection): Trying plugin ACT Apricot Disk Image
DEBUG (Format detection): Trying plugin Alcohol 120% Media Descriptor Structure
DEBUG (Format detection): Trying plugin Anex86 Disk Image
DEBUG (Anex86 plugin): fdihdr.unknown = 0
DEBUG (Anex86 plugin): fdihdr.hddtype = 0
DEBUG (Anex86 plugin): fdihdr.hdrSize = 0
DEBUG (Anex86 plugin): fdihdr.dskSize = 0
DEBUG (Anex86 plugin): fdihdr.bps = 0
DEBUG (Anex86 plugin): fdihdr.spt = 0
DEBUG (Anex86 plugin): fdihdr.heads = 0
DEBUG (Anex86 plugin): fdihdr.cylinders = 0
DEBUG (Format detection): Trying plugin Apple ][ Interleaved Disk Image
DEBUG (Format detection): Trying plugin Apple 2IMG
DEBUG (Format detection): Trying plugin Apple Disk Archival/Retrieval Tool
DEBUG (Format detection): Trying plugin Apple DiskCopy 4.2
DEBUG (DC42 plugin): tmp_header.diskName = ""
DEBUG (DC42 plugin): tmp_header.dataSize = 0 bytes
DEBUG (DC42 plugin): tmp_header.tagSize = 0 bytes
DEBUG (DC42 plugin): tmp_header.dataChecksum = 0x00000000
DEBUG (DC42 plugin): tmp_header.tagChecksum = 0x00000000
DEBUG (DC42 plugin): tmp_header.format = 0x00
DEBUG (DC42 plugin): tmp_header.fmtByte = 0x00
DEBUG (DC42 plugin): tmp_header.valid = 0
DEBUG (DC42 plugin): tmp_header.reserved = 0
DEBUG (Format detection): Trying plugin Apple New Disk Image Format
DEBUG (Format detection): Trying plugin Apple NIB
DEBUG (Format detection): Trying plugin Apple Universal Disk Image Format
DEBUG (Format detection): Trying plugin Basic Lisa Utility
DEBUG (Format detection): Trying plugin BlindWrite 4
DEBUG (Format detection): Trying plugin BlindWrite 5
DEBUG (Format detection): Trying plugin CDRDAO tocfile
DEBUG (Format detection): Trying plugin CDRWin cuesheet
DEBUG (Format detection): Trying plugin CisCopy Disk Image (DC-File)
DEBUG (Format detection): Trying plugin CloneCD
DEBUG (Format detection): Trying plugin CopyTape
DEBUG (Format detection): Trying plugin CPCEMU Disk-File and Extended CPC Disk-File
DEBUG (CPCDSK plugin): header.magic = ""
DEBUG (Format detection): Trying plugin d2f disk image
DEBUG (Format detection): Trying plugin D88 Disk Image
DEBUG (D88 plugin): d88hdr.name = ""
DEBUG (D88 plugin): d88hdr.reserved is empty? = True
DEBUG (D88 plugin): d88hdr.write_protect = 0x00
DEBUG (D88 plugin): d88hdr.disk_type = D2 (0)
DEBUG (D88 plugin): d88hdr.disk_size = 0
DEBUG (Format detection): Trying plugin Digital Research DiskCopy
DEBUG (Format detection): Trying plugin DIM Disk Image
DEBUG (Format detection): Trying plugin DiscFerret
DEBUG (Format detection): Trying plugin DiscJuggler
DEBUG (DiscJuggler plugin): dscLen = 0
DEBUG (Format detection): Trying plugin DiskDupe DDI Disk Image
DEBUG (Format detection): Trying plugin Dreamcast GDI image
DEBUG (Format detection): Trying plugin Dunfield's IMD
DEBUG (Format detection): Trying plugin HD-Copy disk image
DEBUG (Format detection): Trying plugin IBM SaveDskF
DEBUG (Format detection): Trying plugin KryoFlux STREAM
DEBUG (Format detection): Trying plugin MAME Compressed Hunks of Data
DEBUG (Format detection): Trying plugin MAXI Disk image
DEBUG (MAXI Disk plugin): tmp_header.unknown = 0
DEBUG (MAXI Disk plugin): tmp_header.diskType = 0
DEBUG (MAXI Disk plugin): tmp_header.heads = 0
DEBUG (MAXI Disk plugin): tmp_header.cylinders = 0
DEBUG (MAXI Disk plugin): tmp_header.bytesPerSector = 0
DEBUG (MAXI Disk plugin): tmp_header.sectorsPerTrack = 0
DEBUG (MAXI Disk plugin): tmp_header.unknown2 = 0
DEBUG (MAXI Disk plugin): tmp_header.unknown3 = 0
DEBUG (Format detection): Trying plugin Microsoft VHDX
DEBUG (Format detection): Trying plugin Nero Burning ROM image
DEBUG (Nero plugin): imageStream.Length = 149979136
DEBUG (Nero plugin): footerV1.ChunkID = 0x00000000
DEBUG (Nero plugin): footerV1.FirstChunkOffset = 0
DEBUG (Nero plugin): footerV2.ChunkID = 0x00000000
DEBUG (Nero plugin): footerV2.FirstChunkOffset = 0
DEBUG (Format detection): Trying plugin Parallels disk image
DEBUG (Format detection): Trying plugin PartClone disk image
DEBUG (Format detection): Trying plugin Partimage disk image
DEBUG (Format detection): Trying plugin QEMU Copy-On-Write disk image
DEBUG (Format detection): Trying plugin QEMU Copy-On-Write disk image v2
DEBUG (QCOW plugin): qHdr.magic = 0x00000000
DEBUG (QCOW plugin): qHdr.version = 0
DEBUG (Format detection): Trying plugin QEMU Enhanced Disk image
DEBUG (Format detection): Trying plugin Ray Arachelian's Disk IMage
DEBUG (Ray Arachelian's Disk IMage plugin): header.signature =
DEBUG (Ray Arachelian's Disk IMage plugin): header.diskType = 0
DEBUG (Ray Arachelian's Disk IMage plugin): header.heads = 0
DEBUG (Ray Arachelian's Disk IMage plugin): header.cylinders = 0
DEBUG (Ray Arachelian's Disk IMage plugin): header.sectorsPerTrack = 0
DEBUG (Ray Arachelian's Disk IMage plugin): header.signature matches? = False
DEBUG (Format detection): Trying plugin RS-IDE Hard Disk Image
DEBUG (Format detection): Trying plugin Spectrum Floppy Disk Image
DEBUG (Format detection): Trying plugin SuperCardPro
DEBUG (Format detection): Trying plugin Sydex CopyQM
DEBUG (Format detection): Trying plugin Sydex TeleDisk
DEBUG (Format detection): Trying plugin T98 Hard Disk Image
DEBUG (T98 plugin): cylinders = 0
DEBUG (Format detection): Trying plugin T98-Next NHD r0 Disk Image
DEBUG (Format detection): Trying plugin Virtual98 Disk Image
DEBUG (Format detection): Trying plugin VirtualBox Disk Image
DEBUG (Format detection): Trying plugin VirtualPC
DEBUG (Format detection): Trying plugin VMware disk image
DEBUG (Format detection): Trying plugin Raw Disk Image
Input image format identified by Raw Disk Image.
DEBUG (ZZZRawImage Plugin): Found media tag CD_FullTOC
DEBUG (Convert-image command): Correctly opened image file.
DEBUG (Convert-image command): Image without headers is 149979136 bytes.
DEBUG (Convert-image command): Image has 73232 sectors.
DEBUG (Convert-image command): Image identifies media type as CD.
Output image format: Alcohol 120% Media Descriptor Structure.
Converting media tag CD_FullTOC
73232 sectors to convert
Converting sectors 73232 to 73232 in track 1 (100,00% done)
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Aaru.Core.Media.CompactDisc.GenerateSubchannels(HashSet`1 subchannelExtents, Track[] tracks, Dictionary`2 trackFlags, UInt64 blocks, SubchannelLog subLog,
 DumpLog dumpLog, InitProgressHandler initProgress, UpdateProgressHandler updateProgress, EndProgressHandler endProgress, IWritableImage outputPlugin) in C:\pro
jects\aaru\Aaru.Core\Media\CompactDisc.cs:line 1624
   at Aaru.Commands.Image.ConvertImageCommand.Invoke(Boolean verbose, Boolean debug, String cicmXml, String comments, Int32 count, String creator, String driveF
irmwareRevision, String driveManufacturer, String driveModel, String driveSerialNumber, Boolean force, String inputPath, Int32 lastMediaSequence, String mediaBa
rcode, String mediaManufacturer, String mediaModel, String mediaPartNumber, Int32 mediaSequence, String mediaSerialNumber, String mediaTitle, String outputPath,
 String options, String resumeFile, String format, String geometry, Boolean fixSubchannelPosition, Boolean fixSubchannel, Boolean fixSubchannelCrc, Boolean gene
rateSubchannels) in C:\projects\aaru\Aaru\Commands\Image\Convert.cs:line 1047
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
Uploading statistics
```

The image I used for testing can be found [here](https://archive.org/details/lernpaket-mathematik-klasse-3-4) but I guess any other image will do as well. First convert the MDS/MDF to ISO with `--force`, then try the command line above to convert it back to MDS+MDF

**Comment by SilasLaspada** [comment]
Can reproduce, this disc crashes in the same way as well https://archive.org/details/driversoftwareformemorystickreaderwriterspvd-003usbdriver2000
