### ISSUE TITLE
[FAT filesystem] Exception mounting FAT12 volume from PC-DOS 2.00

### ISSUE THREAD

**Issue by claunia** [aaru-dps/Aaru#596]
### Prerequisites

* [x] Are you running the latest version?
* [x] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [x] I was running Aaru under Linux 5.12.7-arch1-1...
* [x] ...in 64-bit
* [x] ...using an Intel / AMD processor

### Description
Exception mounting FAT12 from PC-DOS 2.00.

### Exact command line used:
Test unit.

### Expected behavior:
Mounted correctly.

### Actual behavior:
Exception

### Command output:
```
System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at Aaru.Filesystems.FAT.Mount(IMediaImage imagePlugin, Partition partition, Encoding encoding, Dictionary`2 options, String namespace) in /home/claunia/Development/Aaru/Aaru/Aaru.Filesystems/FAT/Super.cs:line 750
   at Aaru.Tests.Filesystems.ReadOnlyFilesystemTest.Build() in /home/claunia/Development/Aaru/Aaru/Aaru.Tests/Filesystems/ReadOnlyFilesystemTest.cs:line 218
```

**Comment by claunia** [comment]
Also occurs with PC-DOS 2.10, Mac OS X 10.4, Mac OS X 10.11 and NetBSD 6.1.5 volumes.
