### ISSUE TITLE
[Aaru Format] "Requested more sectors than present in track, won't cross tracks" trying to read from an Aaru Format image of a specific multi-session disc

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#615]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [ ] I was running Aaru under Linux [version here]...
* [ ] I was running Aaru under macOS [version here]...
* [ ] ...in 32-bit
* [X] ...in 64-bit
* [X] ...using an Intel / AMD processor
* [ ] ...using an ARM or Apple Silicon processor
    * **Image format**: Aaru Format 
    * **Application that created the image**: Aaru
* [ ] I was converting the image...
    * ...**Destination image format**:
* [ ] I was listing the filesystem contents...
* [ ] I was extracting the filesystem contents...
    * ...**Filesystem**:
    * [ ] Analyze command recognizes the filesystem
* [ ] I was creating a metadata sidecar
* [ ] I was checksumming the image
* [X] I was verifying the image

### Description

When reading from an Aaru Format image, Aaru errors out with "Requested more sectors (141584) than present in track (30424), won't cross tracks (Parameter 'length')". This includes when checksumming the image during a dump, but can be seen on multiple occasions, including converting, comparing, or verifying the image. 

### Exact command line used:

`aaru i verify .\OEP_Plextor.aaruf`

### Output of command execution with debug output enabled
```
aaru 5.2.99.3380-alpha+4ec6710b built by DESKTOP-8B4K7NM in Debug, modified
Copyright c 2011-2021 Natalia Portillo

Disc image checksums are correct
Checking sector 141368 of 314652, on track 7Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Requested more sectors (141584) than present in track (30424), won't cross tracks (Parameter 'length')
   at Aaru.DiscImages.AaruFormat.ReadSectorsLong(UInt64 sectorAddress, UInt32 length) in C:\Users\silas\Desktop\GIT\Aaru\Aaru.Images\AaruFormat\Read.cs:line 2071
   at Aaru.DiscImages.AaruFormat.ReadSectorsLong(UInt64 sectorAddress, UInt32 length, UInt32 track) in C:\Users\silas\Desktop\GIT\Aaru\Aaru.Images\AaruFormat\Read.cs:line 2221
   at Aaru.DiscImages.AaruFormat.VerifySectors(UInt64 sectorAddress, UInt32 length, UInt32 track, List`1& failingLbas, List`1& unknownLbas) in C:\Users\silas\Desktop\GIT\Aaru\Aaru.Images\AaruFormat\Verify.cs:line 278
   at Aaru.Commands.Image.VerifyCommand.Invoke(Boolean debug, Boolean verbose, String imagePath, Boolean verifyDisc, Boolean verifySectors) in C:\Users\silas\Desktop\GIT\Aaru\Aaru\Commands\Image\Verify.cs:line 197
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Image

https://we.tl/t-tzMYuOv1hW

**Comment by claunia** [comment]
Dumping fixed in 7d289dc9e39688d43a944d0ccfd1946abea3e05c
